const municipios = [
        // Amazonas
        { value: 'Leticia', label: 'Leticia', departamento: 'Amazonas' },
        { value: 'Puerto Nariño', label: 'Puerto Nariño', departamento: 'Amazonas' },
        { value: 'Tarapacá', label: 'Tarapacá', departamento: 'Amazonas' },
      
        // Antioquia
        { value: 'Abejorral', label: 'Abejorral', departamento: 'Antioquia' },
        { value: 'Abriaquí', label: 'Abriaquí', departamento: 'Antioquia' },
        { value: 'Alejandría', label: 'Alejandría', departamento: 'Antioquia' },
        { value: 'Amagá', label: 'Amagá', departamento: 'Antioquia' },
        { value: 'Amalfi', label: 'Amalfi', departamento: 'Antioquia' },
        { value: 'Andes', label: 'Andes', departamento: 'Antioquia' },
        { value: 'Angelópolis', label: 'Angelópolis', departamento: 'Antioquia' },
        { value: 'Angostura', label: 'Angostura', departamento: 'Antioquia' },
        { value: 'Anorí', label: 'Anorí', departamento: 'Antioquia' },
        { value: 'Anzá', label: 'Anzá', departamento: 'Antioquia' },
        { value: 'Apartadó', label: 'Apartadó', departamento: 'Antioquia' },
        { value: 'Arboletes', label: 'Arboletes', departamento: 'Antioquia' },
        { value: 'Argelia', label: 'Argelia', departamento: 'Antioquia' },
        { value: 'Armenia', label: 'Armenia', departamento: 'Antioquia' },
        { value: 'Barbosa', label: 'Barbosa', departamento: 'Antioquia' },
        { value: 'Bello', label: 'Bello', departamento: 'Antioquia' },
        { value: 'Belmira', label: 'Belmira', departamento: 'Antioquia' },
        { value: 'Betania', label: 'Betania', departamento: 'Antioquia' },
        { value: 'Betulia', label: 'Betulia', departamento: 'Antioquia' },
        { value: 'Briceño', label: 'Briceño', departamento: 'Antioquia' },
        { value: 'Buriticá', label: 'Buriticá', departamento: 'Antioquia' },
        { value: 'Cáceres', label: 'Cáceres', departamento: 'Antioquia' },
        { value: 'Caicedo', label: 'Caicedo', departamento: 'Antioquia' },
        { value: 'Caldas', label: 'Caldas', departamento: 'Antioquia' },
        { value: 'Campamento', label: 'Campamento', departamento: 'Antioquia' },
        { value: 'Cañasgordas', label: 'Cañasgordas', departamento: 'Antioquia' },
        { value: 'Caracolí', label: 'Caracolí', departamento: 'Antioquia' },
        { value: 'Caramanta', label: 'Caramanta', departamento: 'Antioquia' },
        { value: 'Carepa', label: 'Carepa', departamento: 'Antioquia' },
        { value: 'Carolina', label: 'Carolina', departamento: 'Antioquia' },
        { value: 'Caucasia', label: 'Caucasia', departamento: 'Antioquia' },
        { value: 'Chigorodó', label: 'Chigorodó', departamento: 'Antioquia' },
        { value: 'Cisneros', label: 'Cisneros', departamento: 'Antioquia' },
        { value: 'Ciudad Bolívar', label: 'Ciudad Bolívar', departamento: 'Antioquia' },
        { value: 'Cocorná', label: 'Cocorná', departamento: 'Antioquia' },
        { value: 'Concepción', label: 'Concepción', departamento: 'Antioquia' },
        { value: 'Concordia', label: 'Concordia', departamento: 'Antioquia' },
        { value: 'Copacabana', label: 'Copacabana', departamento: 'Antioquia' },
        { value: 'Dabeiba', label: 'Dabeiba', departamento: 'Antioquia' },
        { value: 'Donmatías', label: 'Donmatías', departamento: 'Antioquia' },
        { value: 'Ebéjico', label: 'Ebéjico', departamento: 'Antioquia' },
        { value: 'El Bagre', label: 'El Bagre', departamento: 'Antioquia' },
        { value: 'El Carmen de Viboral', label: 'El Carmen de Viboral', departamento: 'Antioquia' },
        { value: 'El Peñol', label: 'El Peñol', departamento: 'Antioquia' },
        { value: 'El Retiro', label: 'El Retiro', departamento: 'Antioquia' },
        { value: 'El Santuario', label: 'El Santuario', departamento: 'Antioquia' },
        { value: 'Entrerríos', label: 'Entrerríos', departamento: 'Antioquia' },
        { value: 'Envigado', label: 'Envigado', departamento: 'Antioquia' },
        { value: 'Fredonia', label: 'Fredonia', departamento: 'Antioquia' },
        { value: 'Frontino', label: 'Frontino', departamento: 'Antioquia' },
        { value: 'Giraldo', label: 'Giraldo', departamento: 'Antioquia' },
        { value: 'Girardota', label: 'Girardota', departamento: 'Antioquia' },
        { value: 'Gómez Plata', label: 'Gómez Plata', departamento: 'Antioquia' },
        { value: 'Granada', label: 'Granada', departamento: 'Antioquia' },
        { value: 'Guadalupe', label: 'Guadalupe', departamento: 'Antioquia' },
        { value: 'Guarne', label: 'Guarne', departamento: 'Antioquia' },
        { value: 'Guatapé', label: 'Guatapé', departamento: 'Antioquia' },
        { value: 'Heliconia', label: 'Heliconia', departamento: 'Antioquia' },
        { value: 'Hispania', label: 'Hispania', departamento: 'Antioquia' },
        { value: 'Itagüí', label: 'Itagüí', departamento: 'Antioquia' },
        { value: 'Ituango', label: 'Ituango', departamento: 'Antioquia' },
        { value: 'Jardín', label: 'Jardín', departamento: 'Antioquia' },
        { value: 'Jericó', label: 'Jericó', departamento: 'Antioquia' },
        { value: 'La Ceja', label: 'La Ceja', departamento: 'Antioquia' },
        { value: 'La Estrella', label: 'La Estrella', departamento: 'Antioquia' },
        { value: 'La Pintada', label: 'La Pintada', departamento: 'Antioquia' },
        { value: 'La Unión', label: 'La Unión', departamento: 'Antioquia' },
        { value: 'Liborina', label: 'Liborina', departamento: 'Antioquia' },
        { value: 'Maceo', label: 'Maceo', departamento: 'Antioquia' },
        { value: 'Marinilla', label: 'Marinilla', departamento: 'Antioquia' },
        { value: 'Medellín', label: 'Medellín', departamento: 'Antioquia' },
        { value: 'Montebello', label: 'Montebello', departamento: 'Antioquia' },
        { value: 'Murindó', label: 'Murindó', departamento: 'Antioquia' },
        { value: 'Mutatá', label: 'Mutatá', departamento: 'Antioquia' },
        { value: 'Nariño', label: 'Nariño', departamento: 'Antioquia' },
        { value: 'Nechí', label: 'Nechí', departamento: 'Antioquia' },
        { value: 'Necoclí', label: 'Necoclí', departamento: 'Antioquia' },
        { value: 'Olaya', label: 'Olaya', departamento: 'Antioquia' },
        { value: 'Peque', label: 'Peque', departamento: 'Antioquia' },
        { value: 'Pueblorrico', label: 'Pueblorrico', departamento: 'Antioquia' },
        { value: 'Puerto Berrío', label: 'Puerto Berrío', departamento: 'Antioquia' },
        { value: 'Puerto Nare', label: 'Puerto Nare', departamento: 'Antioquia' },
        { value: 'Puerto Triunfo', label: 'Puerto Triunfo', departamento: 'Antioquia' },
        { value: 'Remedios', label: 'Remedios', departamento: 'Antioquia' },
        { value: 'Rionegro', label: 'Rionegro', departamento: 'Antioquia' },
        { value: 'Sabanalarga', label: 'Sabanalarga', departamento: 'Antioquia' },
        { value: 'Sabaneta', label: 'Sabaneta', departamento: 'Antioquia' },
        { value: 'Salgar', label: 'Salgar', departamento: 'Antioquia' },
        { value: 'San Andrés de Cuerquía', label: 'San Andrés de Cuerquía', departamento: 'Antioquia' },
        { value: 'San Carlos', label: 'San Carlos', departamento: 'Antioquia' },
        { value: 'San Francisco', label: 'San Francisco', departamento: 'Antioquia' },
        { value: 'San Jerónimo', label: 'San Jerónimo', departamento: 'Antioquia' },
        { value: 'San José de la Montaña', label: 'San José de la Montaña', departamento: 'Antioquia' },
        { value: 'San Juan de Urabá', label: 'San Juan de Urabá', departamento: 'Antioquia' },
        { value: 'San Luis', label: 'San Luis', departamento: 'Antioquia' },
        { value: 'San Pedro de Urabá', label: 'San Pedro de Urabá', departamento: 'Antioquia' },
        { value: 'San Pedro de los Milagros', label: 'San Pedro de los Milagros', departamento: 'Antioquia' },
        { value: 'San Rafael', label: 'San Rafael', departamento: 'Antioquia' },
        { value: 'San Roque', label: 'San Roque', departamento: 'Antioquia' },
        { value: 'San Vicente', label: 'San Vicente', departamento: 'Antioquia' },
        { value: 'Santa Bárbara', label: 'Santa Bárbara', departamento: 'Antioquia' },
        { value: 'Santa Fe de Antioquia', label: 'Santa Fe de Antioquia', departamento: 'Antioquia' },
        { value: 'Santa Rosa de Osos', label: 'Santa Rosa de Osos', departamento: 'Antioquia' },
        { value: 'Santo Domingo', label: 'Santo Domingo', departamento: 'Antioquia' },
        { value: 'Segovia', label: 'Segovia', departamento: 'Antioquia' },
        { value: 'Sonsón', label: 'Sonsón', departamento: 'Antioquia' },
        { value: 'Sopetrán', label: 'Sopetrán', departamento: 'Antioquia' },
        { value: 'Támesis', label: 'Támesis', departamento: 'Antioquia' },
        { value: 'Tarazá', label: 'Tarazá', departamento: 'Antioquia' },
        { value: 'Tarso', label: 'Tarso', departamento: 'Antioquia' },
        { value: 'Titiribí', label: 'Titiribí', departamento: 'Antioquia' },
        { value: 'Toledo', label: 'Toledo', departamento: 'Antioquia' },
        { value: 'Turbo', label: 'Turbo', departamento: 'Antioquia' },
        { value: 'Uramita', label: 'Uramita', departamento: 'Antioquia' },
        { value: 'Urrao', label: 'Urrao', departamento: 'Antioquia' },
        { value: 'Valdivia', label: 'Valdivia', departamento: 'Antioquia' },
        { value: 'Valparaíso', label: 'Valparaíso', departamento: 'Antioquia' },
        { value: 'Vegachí', label: 'Vegachí', departamento: 'Antioquia' },
        { value: 'Venecia', label: 'Venecia', departamento: 'Antioquia' },
        { value: 'Vigía del Fuerte', label: 'Vigía del Fuerte', departamento: 'Antioquia' },
        { value: 'Yalí', label: 'Yalí', departamento: 'Antioquia' },
        { value: 'Yarumal', label: 'Yarumal', departamento: 'Antioquia' },
        { value: 'Yolombó', label: 'Yolombó', departamento: 'Antioquia' },
        { value: 'Yondó', label: 'Yondó', departamento: 'Antioquia' },
        { value: 'Zaragoza', label: 'Zaragoza', departamento: 'Antioquia' },
      
        // Arauca
        { value: 'Arauca', label: 'Arauca', departamento: 'Arauca' },
        { value: 'Arauquita', label: 'Arauquita', departamento: 'Arauca' },
        { value: 'Cravo Norte', label: 'Cravo Norte', departamento: 'Arauca' },
        { value: 'Fortul', label: 'Fortul', departamento: 'Arauca' },
        { value: 'Puerto Rondón', label: 'Puerto Rondón', departamento: 'Arauca' },
        { value: 'Saravena', label: 'Saravena', departamento: 'Arauca' },
        { value: 'Tame', label: 'Tame', departamento: 'Arauca' },
      
        // Atlántico
        { value: 'Baranoa', label: 'Baranoa', departamento: 'Atlántico' },
        { value: 'Barranquilla', label: 'Barranquilla', departamento: 'Atlántico' },
        { value: 'Campo de la Cruz', label: 'Campo de la Cruz', departamento: 'Atlántico' },
        { value: 'Candelaria', label: 'Candelaria', departamento: 'Atlántico' },
        { value: 'Galapa', label: 'Galapa', departamento: 'Atlántico' },
        { value: 'Juan de Acosta', label: 'Juan de Acosta', departamento: 'Atlántico' },
        { value: 'Luruaco', label: 'Luruaco', departamento: 'Atlántico' },
        { value: 'Malambo', label: 'Malambo', departamento: 'Atlántico' },
        { value: 'Manatí', label: 'Manatí', departamento: 'Atlántico' },
        { value: 'Palmar de Varela', label: 'Palmar de Varela', departamento: 'Atlántico' },
        { value: 'Piojó', label: 'Piojó', departamento: 'Atlántico' },
        { value: 'Polonuevo', label: 'Polonuevo', departamento: 'Atlántico' },
        { value: 'Ponedera', label: 'Ponedera', departamento: 'Atlántico' },
        { value: 'Puerto Colombia', label: 'Puerto Colombia', departamento: 'Atlántico' },
        { value: 'Repelón', label: 'Repelón', departamento: 'Atlántico' },
        { value: 'Sabanagrande', label: 'Sabanagrande', departamento: 'Atlántico' },
        { value: 'Sabanalarga', label: 'Sabanalarga', departamento: 'Atlántico' },
        { value: 'Santa Lucía', label: 'Santa Lucía', departamento: 'Atlántico' },
        { value: 'Santo Tomás', label: 'Santo Tomás', departamento: 'Atlántico' },
        { value: 'Soledad', label: 'Soledad', departamento: 'Atlántico' },
        { value: 'Suan', label: 'Suan', departamento: 'Atlántico' },
        { value: 'Tubará', label: 'Tubará', departamento: 'Atlántico' },
        { value: 'Usiacurí', label: 'Usiacurí', departamento: 'Atlántico' },
      
        // Bolívar
        { value: 'Achí', label: 'Achí', departamento: 'Bolívar' },
        { value: 'Altos del Rosario', label: 'Altos del Rosario', departamento: 'Bolívar' },
        { value: 'Arenal', label: 'Arenal', departamento: 'Bolívar' },
        { value: 'Arjona', label: 'Arjona', departamento: 'Bolívar' },
        { value: 'Arroyohondo', label: 'Arroyohondo', departamento: 'Bolívar' },
        { value: 'Barranco de Loba', label: 'Barranco de Loba', departamento: 'Bolívar' },
        { value: 'Calamar', label: 'Calamar', departamento: 'Bolívar' },
        { value: 'Cantagallo', label: 'Cantagallo', departamento: 'Bolívar' },
        { value: 'Cartagena', label: 'Cartagena', departamento: 'Bolívar' },
        { value: 'Cicuco', label: 'Cicuco', departamento: 'Bolívar' },
        { value: 'Clemencia', label: 'Clemencia', departamento: 'Bolívar' },
        { value: 'Córdoba', label: 'Córdoba', departamento: 'Bolívar' },
        { value: 'El Carmen de Bolívar', label: 'El Carmen de Bolívar', departamento: 'Bolívar' },
        { value: 'El Guamo', label: 'El Guamo', departamento: 'Bolívar' },
        { value: 'El Peñón', label: 'El Peñón', departamento: 'Bolívar' },
        { value: 'Hatillo de Loba', label: 'Hatillo de Loba', departamento: 'Bolívar' },
        { value: 'Magangué', label: 'Magangué', departamento: 'Bolívar' },
        { value: 'Mahates', label: 'Mahates', departamento: 'Bolívar' },
        { value: 'Margarita', label: 'Margarita', departamento: 'Bolívar' },
        { value: 'María la Baja', label: 'María la Baja', departamento: 'Bolívar' },
        { value: 'Mompós', label: 'Mompós', departamento: 'Bolívar' },
        { value: 'Montecristo', label: 'Montecristo', departamento: 'Bolívar' },
        { value: 'Morales', label: 'Morales', departamento: 'Bolívar' },
        { value: 'Norosí', label: 'Norosí', departamento: 'Bolívar' },
        { value: 'Pinillos', label: 'Pinillos', departamento: 'Bolívar' },
        { value: 'Regidor', label: 'Regidor', departamento: 'Bolívar' },
        { value: 'Río Viejo', label: 'Río Viejo', departamento: 'Bolívar' },
        { value: 'San Cristóbal', label: 'San Cristóbal', departamento: 'Bolívar' },
        { value: 'San Estanislao', label: 'San Estanislao', departamento: 'Bolívar' },
        { value: 'San Fernando', label: 'San Fernando', departamento: 'Bolívar' },
        { value: 'San Jacinto', label: 'San Jacinto', departamento: 'Bolívar' },
        { value: 'San Jacinto del Cauca', label: 'San Jacinto del Cauca', departamento: 'Bolívar' },
        { value: 'San Juan Nepomuceno', label: 'San Juan Nepomuceno', departamento: 'Bolívar' },
        { value: 'San Martín de Loba', label: 'San Martín de Loba', departamento: 'Bolívar' },
        { value: 'San Pablo', label: 'San Pablo', departamento: 'Bolívar' },
        { value: 'Santa Catalina', label: 'Santa Catalina', departamento: 'Bolívar' },
        { value: 'Santa Rosa', label: 'Santa Rosa', departamento: 'Bolívar' },
        { value: 'Santa Rosa del Sur', label: 'Santa Rosa del Sur', departamento: 'Bolívar' },
        { value: 'Simití', label: 'Simití', departamento: 'Bolívar' },
        { value: 'Soplaviento', label: 'Soplaviento', departamento: 'Bolívar' },
        { value: 'Talaigua Nuevo', label: 'Talaigua Nuevo', departamento: 'Bolívar' },
        { value: 'Tiquisio', label: 'Tiquisio', departamento: 'Bolívar' },
        { value: 'Turbaco', label: 'Turbaco', departamento: 'Bolívar' },
        { value: 'Turbaná', label: 'Turbaná', departamento: 'Bolívar' },
        { value: 'Villanueva', label: 'Villanueva', departamento: 'Bolívar' },
        { value: 'Zambrano', label: 'Zambrano', departamento: 'Bolívar' },
      
        // Boyacá
        { value: 'Almeida', label: 'Almeida', departamento: 'Boyacá' },
        { value: 'Aquitania', label: 'Aquitania', departamento: 'Boyacá' },
        { value: 'Arcabuco', label: 'Arcabuco', departamento: 'Boyacá' },
        { value: 'Belén', label: 'Belén', departamento: 'Boyacá' },
        { value: 'Berbeo', label: 'Berbeo', departamento: 'Boyacá' },
        { value: 'Betéitiva', label: 'Betéitiva', departamento: 'Boyacá' },
        { value: 'Boavita', label: 'Boavita', departamento: 'Boyacá' },
        { value: 'Boyacá', label: 'Boyacá', departamento: 'Boyacá' },
        { value: 'Briceño', label: 'Briceño', departamento: 'Boyacá' },
        { value: 'Buenavista', label: 'Buenavista', departamento: 'Boyacá' },
        { value: 'Busbanzá', label: 'Busbanzá', departamento: 'Boyacá' },
        { value: 'Caldas', label: 'Caldas', departamento: 'Boyacá' },
        { value: 'Campohermoso', label: 'Campohermoso', departamento: 'Boyacá' },
        { value: 'Cerinza', label: 'Cerinza', departamento: 'Boyacá' },
        { value: 'Chinavita', label: 'Chinavita', departamento: 'Boyacá' },
        { value: 'Chiquinquirá', label: 'Chiquinquirá', departamento: 'Boyacá' },
        { value: 'Chíquiza', label: 'Chíquiza', departamento: 'Boyacá' },
        { value: 'Chiscas', label: 'Chiscas', departamento: 'Boyacá' },
        { value: 'Chita', label: 'Chita', departamento: 'Boyacá' },
        { value: 'Chitaraque', label: 'Chitaraque', departamento: 'Boyacá' },
        { value: 'Chivatá', label: 'Chivatá', departamento: 'Boyacá' },
        { value: 'Ciénega', label: 'Ciénega', departamento: 'Boyacá' },
        { value: 'Cómbita', label: 'Cómbita', departamento: 'Boyacá' },
        { value: 'Coper', label: 'Coper', departamento: 'Boyacá' },
        { value: 'Corrales', label: 'Corrales', departamento: 'Boyacá' },
        { value: 'Covarachía', label: 'Covarachía', departamento: 'Boyacá' },
        { value: 'Cubará', label: 'Cubará', departamento: 'Boyacá' },
        { value: 'Cucaita', label: 'Cucaita', departamento: 'Boyacá' },
        { value: 'Cuítiva', label: 'Cuítiva', departamento: 'Boyacá' },
        { value: 'Duitama', label: 'Duitama', departamento: 'Boyacá' },
        { value: 'El Cocuy', label: 'El Cocuy', departamento: 'Boyacá' },
        { value: 'El Espino', label: 'El Espino', departamento: 'Boyacá' },
        { value: 'Firavitoba', label: 'Firavitoba', departamento: 'Boyacá' },
        { value: 'Floresta', label: 'Floresta', departamento: 'Boyacá' },
        { value: 'Gachantivá', label: 'Gachantivá', departamento: 'Boyacá' },
        { value: 'Gámeza', label: 'Gámeza', departamento: 'Boyacá' },
        { value: 'Garagoa', label: 'Garagoa', departamento: 'Boyacá' },
        { value: 'Guacamayas', label: 'Guacamayas', departamento: 'Boyacá' },
        { value: 'Guateque', label: 'Guateque', departamento: 'Boyacá' },
        { value: 'Guayatá', label: 'Guayatá', departamento: 'Boyacá' },
        { value: 'Güicán', label: 'Güicán', departamento: 'Boyacá' },
        { value: 'Iza', label: 'Iza', departamento: 'Boyacá' },
        { value: 'Jenesano', label: 'Jenesano', departamento: 'Boyacá' },
        { value: 'Jericó', label: 'Jericó', departamento: 'Boyacá' },
        { value: 'La Capilla', label: 'La Capilla', departamento: 'Boyacá' },
        { value: 'La Uvita', label: 'La Uvita', departamento: 'Boyacá' },
        { value: 'La Victoria', label: 'La Victoria', departamento: 'Boyacá' },
        { value: 'Labranzagrande', label: 'Labranzagrande', departamento: 'Boyacá' },
        { value: 'Macanal', label: 'Macanal', departamento: 'Boyacá' },
        { value: 'Maripí', label: 'Maripí', departamento: 'Boyacá' },
        { value: 'Miraflores', label: 'Miraflores', departamento: 'Boyacá' },
        { value: 'Mongua', label: 'Mongua', departamento: 'Boyacá' },
        { value: 'Monguí', label: 'Monguí', departamento: 'Boyacá' },
        { value: 'Moniquirá', label: 'Moniquirá', departamento: 'Boyacá' },
        { value: 'Motavita', label: 'Motavita', departamento: 'Boyacá' },
        { value: 'Muzo', label: 'Muzo', departamento: 'Boyacá' },
        { value: 'Nobsa', label: 'Nobsa', departamento: 'Boyacá' },
        { value: 'Nuevo Colón', label: 'Nuevo Colón', departamento: 'Boyacá' },
        { value: 'Oicatá', label: 'Oicatá', departamento: 'Boyacá' },
        { value: 'Otanche', label: 'Otanche', departamento: 'Boyacá' },
        { value: 'Pachavita', label: 'Pachavita', departamento: 'Boyacá' },
        { value: 'Páez', label: 'Páez', departamento: 'Boyacá' },
        { value: 'Paipa', label: 'Paipa', departamento: 'Boyacá' },
        { value: 'Pajarito', label: 'Pajarito', departamento: 'Boyacá' },
        { value: 'Panqueba', label: 'Panqueba', departamento: 'Boyacá' },
        { value: 'Pauna', label: 'Pauna', departamento: 'Boyacá' },
        { value: 'Paya', label: 'Paya', departamento: 'Boyacá' },
        { value: 'Paz de Río', label: 'Paz de Río', departamento: 'Boyacá' },
        { value: 'Pesca', label: 'Pesca', departamento: 'Boyacá' },
        { value: 'Pisba', label: 'Pisba', departamento: 'Boyacá' },
        { value: 'Puerto Boyacá', label: 'Puerto Boyacá', departamento: 'Boyacá' },
        { value: 'Quípama', label: 'Quípama', departamento: 'Boyacá' },
        { value: 'Ramiriquí', label: 'Ramiriquí', departamento: 'Boyacá' },
        { value: 'Ráquira', label: 'Ráquira', departamento: 'Boyacá' },
        { value: 'Rondón', label: 'Rondón', departamento: 'Boyacá' },
        { value: 'Saboyá', label: 'Saboyá', departamento: 'Boyacá' },
        { value: 'Sáchica', label: 'Sáchica', departamento: 'Boyacá' },
        { value: 'Samacá', label: 'Samacá', departamento: 'Boyacá' },
        { value: 'San Eduardo', label: 'San Eduardo', departamento: 'Boyacá' },
        { value: 'San José de Pare', label: 'San José de Pare', departamento: 'Boyacá' },
        { value: 'San Luis de Gaceno', label: 'San Luis de Gaceno', departamento: 'Boyacá' },
        { value: 'San Mateo', label: 'San Mateo', departamento: 'Boyacá' },
        { value: 'San Miguel de Sema', label: 'San Miguel de Sema', departamento: 'Boyacá' },
        { value: 'San Pablo de Borbur', label: 'San Pablo de Borbur', departamento: 'Boyacá' },
        { value: 'Santa María', label: 'Santa María', departamento: 'Boyacá' },
        { value: 'Santa Rosa de Viterbo', label: 'Santa Rosa de Viterbo', departamento: 'Boyacá' },
        { value: 'Santa Sofía', label: 'Santa Sofía', departamento: 'Boyacá' },
        { value: 'Santana', label: 'Santana', departamento: 'Boyacá' },
        { value: 'Sativanorte', label: 'Sativanorte', departamento: 'Boyacá' },
        { value: 'Sativasur', label: 'Sativasur', departamento: 'Boyacá' },
        { value: 'Siachoque', label: 'Siachoque', departamento: 'Boyacá' },
        { value: 'Soatá', label: 'Soatá', departamento: 'Boyacá' },
        { value: 'Socha', label: 'Socha', departamento: 'Boyacá' },
        { value: 'Socotá', label: 'Socotá', departamento: 'Boyacá' },
        { value: 'Sogamoso', label: 'Sogamoso', departamento: 'Boyacá' },
        { value: 'Somondoco', label: 'Somondoco', departamento: 'Boyacá' },
        { value: 'Sora', label: 'Sora', departamento: 'Boyacá' },
        { value: 'Soracá', label: 'Soracá', departamento: 'Boyacá' },
        { value: 'Sotaquirá', label: 'Sotaquirá', departamento: 'Boyacá' },
        { value: 'Susacón', label: 'Susacón', departamento: 'Boyacá' },
        { value: 'Sutamarchán', label: 'Sutamarchán', departamento: 'Boyacá' },
        { value: 'Sutatenza', label: 'Sutatenza', departamento: 'Boyacá' },
        { value: 'Tasco', label: 'Tasco', departamento: 'Boyacá' },
        { value: 'Tenza', label: 'Tenza', departamento: 'Boyacá' },
        { value: 'Tibaná', label: 'Tibaná', departamento: 'Boyacá' },
        { value: 'Tibasosa', label: 'Tibasosa', departamento: 'Boyacá' },
        { value: 'Tinjacá', label: 'Tinjacá', departamento: 'Boyacá' },
        { value: 'Tipacoque', label: 'Tipacoque', departamento: 'Boyacá' },
        { value: 'Toca', label: 'Toca', departamento: 'Boyacá' },
        { value: 'Togüí', label: 'Togüí', departamento: 'Boyacá' },
        { value: 'Tópaga', label: 'Tópaga', departamento: 'Boyacá' },
        { value: 'Tota', label: 'Tota', departamento: 'Boyacá' },
        { value: 'Tunja', label: 'Tunja', departamento: 'Boyacá' },
        { value: 'Tununguá', label: 'Tununguá', departamento: 'Boyacá' },
        { value: 'Turmequé', label: 'Turmequé', departamento: 'Boyacá' },
        { value: 'Tuta', label: 'Tuta', departamento: 'Boyacá' },
        { value: 'Tutazá', label: 'Tutazá', departamento: 'Boyacá' },
        { value: 'Umbita', label: 'Umbita', departamento: 'Boyacá' },
        { value: 'Ventaquemada', label: 'Ventaquemada', departamento: 'Boyacá' },
        { value: 'Villa de Leyva', label: 'Villa de Leyva', departamento: 'Boyacá' },
        { value: 'Viracachá', label: 'Viracachá', departamento: 'Boyacá' },
        { value: 'Zetaquira', label: 'Zetaquira', departamento: 'Boyacá' },
      
        // Caldas
        { value: 'Aguadas', label: 'Aguadas', departamento: 'Caldas' },
        { value: 'Anserma', label: 'Anserma', departamento: 'Caldas' },
        { value: 'Aranzazu', label: 'Aranzazu', departamento: 'Caldas' },
        { value: 'Belalcázar', label: 'Belalcázar', departamento: 'Caldas' },
        { value: 'Chinchiná', label: 'Chinchiná', departamento: 'Caldas' },
        { value: 'Filadelfia', label: 'Filadelfia', departamento: 'Caldas' },
        { value: 'La Dorada', label: 'La Dorada', departamento: 'Caldas' },
        { value: 'La Merced', label: 'La Merced', departamento: 'Caldas' },
        { value: 'Manizales', label: 'Manizales', departamento: 'Caldas' },
        { value: 'Manzanares', label: 'Manzanares', departamento: 'Caldas' },
        { value: 'Marmato', label: 'Marmato', departamento: 'Caldas' },
        { value: 'Marquetalia', label: 'Marquetalia', departamento: 'Caldas' },
        { value: 'Marulanda', label: 'Marulanda', departamento: 'Caldas' },
        { value: 'Neira', label: 'Neira', departamento: 'Caldas' },
        { value: 'Norcasia', label: 'Norcasia', departamento: 'Caldas' },
        { value: 'Pácora', label: 'Pácora', departamento: 'Caldas' },
        { value: 'Palestina', label: 'Palestina', departamento: 'Caldas' },
        { value: 'Pensilvania', label: 'Pensilvania', departamento: 'Caldas' },
        { value: 'Riosucio', label: 'Riosucio', departamento: 'Caldas' },
        { value: 'Risaralda', label: 'Risaralda', departamento: 'Caldas' },
        { value: 'Salamina', label: 'Salamina', departamento: 'Caldas' },
        { value: 'Samaná', label: 'Samaná', departamento: 'Caldas' },
        { value: 'San José', label: 'San José', departamento: 'Caldas' },
        { value: 'Supía', label: 'Supía', departamento: 'Caldas' },
        { value: 'Victoria', label: 'Victoria', departamento: 'Caldas' },
        { value: 'Villamaría', label: 'Villamaría', departamento: 'Caldas' },
        { value: 'Viterbo', label: 'Viterbo', departamento: 'Caldas' },
      
        // Caquetá
        { value: 'Albania', label: 'Albania', departamento: 'Caquetá' },
        { value: 'Belén de los Andaquíes', label: 'Belén de los Andaquíes', departamento: 'Caquetá' },
        { value: 'Cartagena del Chairá', label: 'Cartagena del Chairá', departamento: 'Caquetá' },
        { value: 'Curillo', label: 'Curillo', departamento: 'Caquetá' },
        { value: 'El Doncello', label: 'El Doncello', departamento: 'Caquetá' },
        { value: 'El Paujil', label: 'El Paujil', departamento: 'Caquetá' },
        { value: 'Florencia', label: 'Florencia', departamento: 'Caquetá' },
        { value: 'La Montañita', label: 'La Montañita', departamento: 'Caquetá' },
        { value: 'Milán', label: 'Milán', departamento: 'Caquetá' },
        { value: 'Morelia', label: 'Morelia', departamento: 'Caquetá' },
        { value: 'Puerto Rico', label: 'Puerto Rico', departamento: 'Caquetá' },
        { value: 'San José del Fragua', label: 'San José del Fragua', departamento: 'Caquetá' },
        { value: 'San Vicente del Caguán', label: 'San Vicente del Caguán', departamento: 'Caquetá' },
        { value: 'Solano', label: 'Solano', departamento: 'Caquetá' },
        { value: 'Solita', label: 'Solita', departamento: 'Caquetá' },
        { value: 'Valparaíso', label: 'Valparaíso', departamento: 'Caquetá' },
      
        // Casanare
        { value: 'Aguazul', label: 'Aguazul', departamento: 'Casanare' },
        { value: 'Chámeza', label: 'Chámeza', departamento: 'Casanare' },
        { value: 'Hato Corozal', label: 'Hato Corozal', departamento: 'Casanare' },
        { value: 'La Salina', label: 'La Salina', departamento: 'Casanare' },
        { value: 'Maní', label: 'Maní', departamento: 'Casanare' },
        { value: 'Monterrey', label: 'Monterrey', departamento: 'Casanare' },
        { value: 'Nunchía', label: 'Nunchía', departamento: 'Casanare' },
        { value: 'Orocué', label: 'Orocué', departamento: 'Casanare' },
        { value: 'Paz de Ariporo', label: 'Paz de Ariporo', departamento: 'Casanare' },
        { value: 'Pore', label: 'Pore', departamento: 'Casanare' },
        { value: 'Recetor', label: 'Recetor', departamento: 'Casanare' },
        { value: 'Sabanalarga', label: 'Sabanalarga', departamento: 'Casanare' },
        { value: 'Sácama', label: 'Sácama', departamento: 'Casanare' },
        { value: 'San Luis de Palenque', label: 'San Luis de Palenque', departamento: 'Casanare' },
        { value: 'Támara', label: 'Támara', departamento: 'Casanare' },
        { value: 'Tauramena', label: 'Tauramena', departamento: 'Casanare' },
        { value: 'Trinidad', label: 'Trinidad', departamento: 'Casanare' },
        { value: 'Villanueva', label: 'Villanueva', departamento: 'Casanare' },
        { value: 'Yopal', label: 'Yopal', departamento: 'Casanare' },
      
        // Cauca
        { value: 'Almaguer', label: 'Almaguer', departamento: 'Cauca' },
        { value: 'Argelia', label: 'Argelia', departamento: 'Cauca' },
        { value: 'Balboa', label: 'Balboa', departamento: 'Cauca' },
        { value: 'Bolívar', label: 'Bolívar', departamento: 'Cauca' },
        { value: 'Buenos Aires', label: 'Buenos Aires', departamento: 'Cauca' },
        { value: 'Cajibío', label: 'Cajibío', departamento: 'Cauca' },
        { value: 'Caldono', label: 'Caldono', departamento: 'Cauca' },
        { value: 'Caloto', label: 'Caloto', departamento: 'Cauca' },
        { value: 'Corinto', label: 'Corinto', departamento: 'Cauca' },
        { value: 'El Tambo', label: 'El Tambo', departamento: 'Cauca' },
        { value: 'Florencia', label: 'Florencia', departamento: 'Cauca' },
        { value: 'Guachené', label: 'Guachené', departamento: 'Cauca' },
        { value: 'Guapí', label: 'Guapí', departamento: 'Cauca' },
        { value: 'Inzá', label: 'Inzá', departamento: 'Cauca' },
        { value: 'Jambaló', label: 'Jambaló', departamento: 'Cauca' },
        { value: 'La Sierra', label: 'La Sierra', departamento: 'Cauca' },
        { value: 'La Vega', label: 'La Vega', departamento: 'Cauca' },
        { value: 'López', label: 'López', departamento: 'Cauca' },
        { value: 'Mercaderes', label: 'Mercaderes', departamento: 'Cauca' },
        { value: 'Miranda', label: 'Miranda', departamento: 'Cauca' },
        { value: 'Morales', label: 'Morales', departamento: 'Cauca' },
        { value: 'Padilla', label: 'Padilla', departamento: 'Cauca' },
        { value: 'Páez', label: 'Páez', departamento: 'Cauca' },
        { value: 'Patía', label: 'Patía', departamento: 'Cauca' },
        { value: 'Piamonte', label: 'Piamonte', departamento: 'Cauca' },
        { value: 'Piendamó', label: 'Piendamó', departamento: 'Cauca' },
        { value: 'Popayán', label: 'Popayán', departamento: 'Cauca' },
        { value: 'Puerto Tejada', label: 'Puerto Tejada', departamento: 'Cauca' },
        { value: 'Purace', label: 'Purace', departamento: 'Cauca' },
        { value: 'Rosas', label: 'Rosas', departamento: 'Cauca' },
        { value: 'San Sebastián', label: 'San Sebastián', departamento: 'Cauca' },
        { value: 'Santa Rosa', label: 'Santa Rosa', departamento: 'Cauca' },
        { value: 'Santander de Quilichao', label: 'Santander de Quilichao', departamento: 'Cauca' },
        { value: 'Silvia', label: 'Silvia', departamento: 'Cauca' },
        { value: 'Sotará', label: 'Sotará', departamento: 'Cauca' },
        { value: 'Suárez', label: 'Suárez', departamento: 'Cauca' },
        { value: 'Sucre', label: 'Sucre', departamento: 'Cauca' },
        { value: 'Timbío', label: 'Timbío', departamento: 'Cauca' },
        { value: 'Timbiquí', label: 'Timbiquí', departamento: 'Cauca' },
        { value: 'Toribío', label: 'Toribío', departamento: 'Cauca' },
        { value: 'Totoró', label: 'Totoró', departamento: 'Cauca' },
        { value: 'Villa Rica', label: 'Villa Rica', departamento: 'Cauca' },
      
        // Cesar
        { value: 'Aguachica', label: 'Aguachica', departamento: 'Cesar' },
        { value: 'Agustín Codazzi', label: 'Agustín Codazzi', departamento: 'Cesar' },
        { value: 'Astrea', label: 'Astrea', departamento: 'Cesar' },
        { value: 'Becerril', label: 'Becerril', departamento: 'Cesar' },
        { value: 'Bosconia', label: 'Bosconia', departamento: 'Cesar' },
        { value: 'Chimichagua', label: 'Chimichagua', departamento: 'Cesar' },
        { value: 'Chiriguaná', label: 'Chiriguaná', departamento: 'Cesar' },
        { value: 'Curumaní', label: 'Curumaní', departamento: 'Cesar' },
        { value: 'El Copey', label: 'El Copey', departamento: 'Cesar' },
        { value: 'El Paso', label: 'El Paso', departamento: 'Cesar' },
        { value: 'Gamarra', label: 'Gamarra', departamento: 'Cesar' },
        { value: 'González', label: 'González', departamento: 'Cesar' },
        { value: 'La Gloria', label: 'La Gloria', departamento: 'Cesar' },
        { value: 'La Jagua de Ibirico', label: 'La Jagua de Ibirico', departamento: 'Cesar' },
        { value: 'La Paz', label: 'La Paz', departamento: 'Cesar' },
        { value: 'Manaure', label: 'Manaure', departamento: 'Cesar' },
        { value: 'Pailitas', label: 'Pailitas', departamento: 'Cesar' },
        { value: 'Pelaya', label: 'Pelaya', departamento: 'Cesar' },
        { value: 'Pueblo Bello', label: 'Pueblo Bello', departamento: 'Cesar' },
        { value: 'Río de Oro', label: 'Río de Oro', departamento: 'Cesar' },
        { value: 'San Alberto', label: 'San Alberto', departamento: 'Cesar' },
        { value: 'San Diego', label: 'San Diego', departamento: 'Cesar' },
        { value: 'San Martín', label: 'San Martín', departamento: 'Cesar' },
        { value: 'Tamalameque', label: 'Tamalameque', departamento: 'Cesar' },
        { value: 'Valledupar', label: 'Valledupar', departamento: 'Cesar' },
      
        // Chocó
        { value: 'Acandí', label: 'Acandí', departamento: 'Chocó' },
        { value: 'Alto Baudó', label: 'Alto Baudó', departamento: 'Chocó' },
        { value: 'Atrato', label: 'Atrato', departamento: 'Chocó' },
        { value: 'Bagadó', label: 'Bagadó', departamento: 'Chocó' },
        { value: 'Bahía Solano', label: 'Bahía Solano', departamento: 'Chocó' },
        { value: 'Bajo Baudó', label: 'Bajo Baudó', departamento: 'Chocó' },
        { value: 'Bojayá', label: 'Bojayá', departamento: 'Chocó' },
        { value: 'Carmen del Darién', label: 'Carmen del Darién', departamento: 'Chocó' },
        { value: 'Cértegui', label: 'Cértegui', departamento: 'Chocó' },
        { value: 'Condoto', label: 'Condoto', departamento: 'Chocó' },
        { value: 'El Cantón del San Pablo', label: 'El Cantón del San Pablo', departamento: 'Chocó' },
        { value: 'El Carmen de Atrato', label: 'El Carmen de Atrato', departamento: 'Chocó' },
        { value: 'El Litoral del San Juan', label: 'El Litoral del San Juan', departamento: 'Chocó' },
        { value: 'Istmina', label: 'Istmina', departamento: 'Chocó' },
        { value: 'Juradó', label: 'Juradó', departamento: 'Chocó' },
        { value: 'Lloró', label: 'Lloró', departamento: 'Chocó' },
        { value: 'Medio Atrato', label: 'Medio Atrato', departamento: 'Chocó' },
        { value: 'Medio Baudó', label: 'Medio Baudó', departamento: 'Chocó' },
        { value: 'Medio San Juan', label: 'Medio San Juan', departamento: 'Chocó' },
        { value: 'Nóvita', label: 'Nóvita', departamento: 'Chocó' },
        { value: 'Nuquí', label: 'Nuquí', departamento: 'Chocó' },
        { value: 'Quibdó', label: 'Quibdó', departamento: 'Chocó' },
        { value: 'Río Iró', label: 'Río Iró', departamento: 'Chocó' },
        { value: 'Río Quito', label: 'Río Quito', departamento: 'Chocó' },
        { value: 'Riosucio', label: 'Riosucio', departamento: 'Chocó' },
        { value: 'San José del Palmar', label: 'San José del Palmar', departamento: 'Chocó' },
        { value: 'Sipí', label: 'Sipí', departamento: 'Chocó' },
        { value: 'Tadó', label: 'Tadó', departamento: 'Chocó' },
        { value: 'Unguía', label: 'Unguía', departamento: 'Chocó' },
        { value: 'Unión Panamericana', label: 'Unión Panamericana', departamento: 'Chocó' },
      
        // Córdoba
        { value: 'Ayapel', label: 'Ayapel', departamento: 'Córdoba' },
        { value: 'Buenavista', label: 'Buenavista', departamento: 'Córdoba' },
        { value: 'Canalete', label: 'Canalete', departamento: 'Córdoba' },
        { value: 'Cereté', label: 'Cereté', departamento: 'Córdoba' },
        { value: 'Chimá', label: 'Chimá', departamento: 'Córdoba' },
        { value: 'Chinú', label: 'Chinú', departamento: 'Córdoba' },
        { value: 'Ciénaga de Oro', label: 'Ciénaga de Oro', departamento: 'Córdoba' },
        { value: 'Cotorra', label: 'Cotorra', departamento: 'Córdoba' },
        { value: 'La Apartada', label: 'La Apartada', departamento: 'Córdoba' },
        { value: 'Lorica', label: 'Lorica', departamento: 'Córdoba' },
        { value: 'Los Córdobas', label: 'Los Córdobas', departamento: 'Córdoba' },
        { value: 'Momil', label: 'Momil', departamento: 'Córdoba' },
        { value: 'Montelíbano', label: 'Montelíbano', departamento: 'Córdoba' },
        { value: 'Montería', label: 'Montería', departamento: 'Córdoba' },
        { value: 'Moñitos', label: 'Moñitos', departamento: 'Córdoba' },
        { value: 'Planeta Rica', label: 'Planeta Rica', departamento: 'Córdoba' },
        { value: 'Pueblo Nuevo', label: 'Pueblo Nuevo', departamento: 'Córdoba' },
        { value: 'Puerto Escondido', label: 'Puerto Escondido', departamento: 'Córdoba' },
        { value: 'Puerto Libertador', label: 'Puerto Libertador', departamento: 'Córdoba' },
        { value: 'Purísima', label: 'Purísima', departamento: 'Córdoba' },
        { value: 'Sahagún', label: 'Sahagún', departamento: 'Córdoba' },
        { value: 'San Andrés de Sotavento', label: 'San Andrés de Sotavento', departamento: 'Córdoba' },
        { value: 'San Antero', label: 'San Antero', departamento: 'Córdoba' },
        { value: 'San Bernardo del Viento', label: 'San Bernardo del Viento', departamento: 'Córdoba' },
        { value: 'San Carlos', label: 'San Carlos', departamento: 'Córdoba' },
        { value: 'San José de Uré', label: 'San José de Uré', departamento: 'Córdoba' },
        { value: 'San Pelayo', label: 'San Pelayo', departamento: 'Córdoba' },
        { value: 'Tierralta', label: 'Tierralta', departamento: 'Córdoba' },
        { value: 'Tuchín', label: 'Tuchín', departamento: 'Córdoba' },
        { value: 'Valencia', label: 'Valencia', departamento: 'Córdoba' },
      
        // Cundinamarca
        { value: 'Agua de Dios', label: 'Agua de Dios', departamento: 'Cundinamarca' },
        { value: 'Albán', label: 'Albán', departamento: 'Cundinamarca' },
        { value: 'Anapoima', label: 'Anapoima', departamento: 'Cundinamarca' },
        { value: 'Anolaima', label: 'Anolaima', departamento: 'Cundinamarca' },
        { value: 'Apulo', label: 'Apulo', departamento: 'Cundinamarca' },
        { value: 'Arbeláez', label: 'Arbeláez', departamento: 'Cundinamarca' },
        { value: 'Beltrán', label: 'Beltrán', departamento: 'Cundinamarca' },
        { value: 'Bituima', label: 'Bituima', departamento: 'Cundinamarca' },
        { value: 'Bojacá', label: 'Bojacá', departamento: 'Cundinamarca' },
        { value: 'Cabrera', label: 'Cabrera', departamento: 'Cundinamarca' },
        { value: 'Cachipay', label: 'Cachipay', departamento: 'Cundinamarca' },
        { value: 'Cajicá', label: 'Cajicá', departamento: 'Cundinamarca' },
        { value: 'Caparrapí', label: 'Caparrapí', departamento: 'Cundinamarca' },
        { value: 'Cáqueza', label: 'Cáqueza', departamento: 'Cundinamarca' },
        { value: 'Carmen de Carupa', label: 'Carmen de Carupa', departamento: 'Cundinamarca' },
        { value: 'Chaguaní', label: 'Chaguaní', departamento: 'Cundinamarca' },
        { value: 'Chía', label: 'Chía', departamento: 'Cundinamarca' },
        { value: 'Chipaque', label: 'Chipaque', departamento: 'Cundinamarca' },
        { value: 'Choachí', label: 'Choachí', departamento: 'Cundinamarca' },
        { value: 'Chocontá', label: 'Chocontá', departamento: 'Cundinamarca' },
        { value: 'Cogua', label: 'Cogua', departamento: 'Cundinamarca' },
        { value: 'Cota', label: 'Cota', departamento: 'Cundinamarca' },
        { value: 'Cucunubá', label: 'Cucunubá', departamento: 'Cundinamarca' },
        { value: 'El Colegio', label: 'El Colegio', departamento: 'Cundinamarca' },
        { value: 'El Peñón', label: 'El Peñón', departamento: 'Cundinamarca' },
        { value: 'El Rosal', label: 'El Rosal', departamento: 'Cundinamarca' },
        { value: 'Facatativá', label: 'Facatativá', departamento: 'Cundinamarca' },
        { value: 'Fómeque', label: 'Fómeque', departamento: 'Cundinamarca' },
        { value: 'Fosca', label: 'Fosca', departamento: 'Cundinamarca' },
        { value: 'Funza', label: 'Funza', departamento: 'Cundinamarca' },
        { value: 'Fúquene', label: 'Fúquene', departamento: 'Cundinamarca' },
        { value: 'Fusagasugá', label: 'Fusagasugá', departamento: 'Cundinamarca' },
        { value: 'Gachalá', label: 'Gachalá', departamento: 'Cundinamarca' },
        { value: 'Gachancipá', label: 'Gachancipá', departamento: 'Cundinamarca' },
        { value: 'Gachetá', label: 'Gachetá', departamento: 'Cundinamarca' },
        { value: 'Gama', label: 'Gama', departamento: 'Cundinamarca' },
        { value: 'Girardot', label: 'Girardot', departamento: 'Cundinamarca' },
        { value: 'Granada', label: 'Granada', departamento: 'Cundinamarca' },
        { value: 'Guachetá', label: 'Guachetá', departamento: 'Cundinamarca' },
        { value: 'Guaduas', label: 'Guaduas', departamento: 'Cundinamarca' },
        { value: 'Guasca', label: 'Guasca', departamento: 'Cundinamarca' },
        { value: 'Guataquí', label: 'Guataquí', departamento: 'Cundinamarca' },
        { value: 'Guatavita', label: 'Guatavita', departamento: 'Cundinamarca' },
        { value: 'Guayabal de Síquima', label: 'Guayabal de Síquima', departamento: 'Cundinamarca' },
        { value: 'Guayabetal', label: 'Guayabetal', departamento: 'Cundinamarca' },
        { value: 'Gutiérrez', label: 'Gutiérrez', departamento: 'Cundinamarca' },
        { value: 'Jerusalén', label: 'Jerusalén', departamento: 'Cundinamarca' },
        { value: 'Junín', label: 'Junín', departamento: 'Cundinamarca' },
        { value: 'La Calera', label: 'La Calera', departamento: 'Cundinamarca' },
        { value: 'La Mesa', label: 'La Mesa', departamento: 'Cundinamarca' },
        { value: 'La Palma', label: 'La Palma', departamento: 'Cundinamarca' },
        { value: 'La Peña', label: 'La Peña', departamento: 'Cundinamarca' },
        { value: 'La Vega', label: 'La Vega', departamento: 'Cundinamarca' },
        { value: 'Lenguazaque', label: 'Lenguazaque', departamento: 'Cundinamarca' },
        { value: 'Machetá', label: 'Machetá', departamento: 'Cundinamarca' },
        { value: 'Madrid', label: 'Madrid', departamento: 'Cundinamarca' },
        { value: 'Manta', label: 'Manta', departamento: 'Cundinamarca' },
        { value: 'Medina', label: 'Medina', departamento: 'Cundinamarca' },
        { value: 'Mosquera', label: 'Mosquera', departamento: 'Cundinamarca' },
        { value: 'Nariño', label: 'Nariño', departamento: 'Cundinamarca' },
        { value: 'Nemocón', label: 'Nemocón', departamento: 'Cundinamarca' },
        { value: 'Nilo', label: 'Nilo', departamento: 'Cundinamarca' },
        { value: 'Nimaima', label: 'Nimaima', departamento: 'Cundinamarca' },
        { value: 'Nocaima', label: 'Nocaima', departamento: 'Cundinamarca' },
        { value: 'Pacho', label: 'Pacho', departamento: 'Cundinamarca' },
        { value: 'Paime', label: 'Paime', departamento: 'Cundinamarca' },
        { value: 'Pandi', label: 'Pandi', departamento: 'Cundinamarca' },
        { value: 'Paratebueno', label: 'Paratebueno', departamento: 'Cundinamarca' },
        { value: 'Pasca', label: 'Pasca', departamento: 'Cundinamarca' },
        { value: 'Puerto Salgar', label: 'Puerto Salgar', departamento: 'Cundinamarca' },
        { value: 'Pulí', label: 'Pulí', departamento: 'Cundinamarca' },
        { value: 'Quebradanegra', label: 'Quebradanegra', departamento: 'Cundinamarca' },
        { value: 'Quetame', label: 'Quetame', departamento: 'Cundinamarca' },
        { value: 'Quipile', label: 'Quipile', departamento: 'Cundinamarca' },
        { value: 'Ricaurte', label: 'Ricaurte', departamento: 'Cundinamarca' },
        { value: 'San Antonio del Tequendama', label: 'San Antonio del Tequendama', departamento: 'Cundinamarca' },
        { value: 'San Bernardo', label: 'San Bernardo', departamento: 'Cundinamarca' },
        { value: 'San Cayetano', label: 'San Cayetano', departamento: 'Cundinamarca' },
        { value: 'San Francisco', label: 'San Francisco', departamento: 'Cundinamarca' },
        { value: 'San Juan de Río Seco', label: 'San Juan de Río Seco', departamento: 'Cundinamarca' },
        { value: 'Sasaima', label: 'Sasaima', departamento: 'Cundinamarca' },
        { value: 'Sesquilé', label: 'Sesquilé', departamento: 'Cundinamarca' },
        { value: 'Sibaté', label: 'Sibaté', departamento: 'Cundinamarca' },
        { value: 'Silvania', label: 'Silvania', departamento: 'Cundinamarca' },
        { value: 'Simijaca', label: 'Simijaca', departamento: 'Cundinamarca' },
        { value: 'Soacha', label: 'Soacha', departamento: 'Cundinamarca' },
        { value: 'Sopó', label: 'Sopó', departamento: 'Cundinamarca' },
        { value: 'Subachoque', label: 'Subachoque', departamento: 'Cundinamarca' },
        { value: 'Suesca', label: 'Suesca', departamento: 'Cundinamarca' },
        { value: 'Supatá', label: 'Supatá', departamento: 'Cundinamarca' },
        { value: 'Susa', label: 'Susa', departamento: 'Cundinamarca' },
        { value: 'Sutatausa', label: 'Sutatausa', departamento: 'Cundinamarca' },
        { value: 'Tabio', label: 'Tabio', departamento: 'Cundinamarca' },
        { value: 'Tausa', label: 'Tausa', departamento: 'Cundinamarca' },
        { value: 'Tena', label: 'Tena', departamento: 'Cundinamarca' },
        { value: 'Tenjo', label: 'Tenjo', departamento: 'Cundinamarca' },
        { value: 'Tibacuy', label: 'Tibacuy', departamento: 'Cundinamarca' },
        { value: 'Tibirita', label: 'Tibirita', departamento: 'Cundinamarca' },
        { value: 'Tocaima', label: 'Tocaima', departamento: 'Cundinamarca' },
        { value: 'Tocancipá', label: 'Tocancipá', departamento: 'Cundinamarca' },
        { value: 'Topaipí', label: 'Topaipí', departamento: 'Cundinamarca' },
        { value: 'Ubalá', label: 'Ubalá', departamento: 'Cundinamarca' },
        { value: 'Ubaque', label: 'Ubaque', departamento: 'Cundinamarca' },
        { value: 'Ubaté', label: 'Ubaté', departamento: 'Cundinamarca' },
        { value: 'Une', label: 'Une', departamento: 'Cundinamarca' },
        { value: 'Útica', label: 'Útica', departamento: 'Cundinamarca' },
        { value: 'Venecia', label: 'Venecia', departamento: 'Cundinamarca' },
        { value: 'Vergara', label: 'Vergara', departamento: 'Cundinamarca' },
        { value: 'Vianí', label: 'Vianí', departamento: 'Cundinamarca' },
        { value: 'Villagómez', label: 'Villagómez', departamento: 'Cundinamarca' },
        { value: 'Villapinzón', label: 'Villapinzón', departamento: 'Cundinamarca' },
        { value: 'Villeta', label: 'Villeta', departamento: 'Cundinamarca' },
        { value: 'Viotá', label: 'Viotá', departamento: 'Cundinamarca' },
        { value: 'Yacopí', label: 'Yacopí', departamento: 'Cundinamarca' },
        { value: 'Zipacón', label: 'Zipacón', departamento: 'Cundinamarca' },
        { value: 'Zipaquirá', label: 'Zipaquirá', departamento: 'Cundinamarca' },
      
        // Guainía
        { value: 'Barranco Minas', label: 'Barranco Minas', departamento: 'Guainía' },
        { value: 'Cacahual', label: 'Cacahual', departamento: 'Guainía' },
        { value: 'Inírida', label: 'Inírida', departamento: 'Guainía' },
        { value: 'La Guadalupe', label: 'La Guadalupe', departamento: 'Guainía' },
        { value: 'Mapiripana', label: 'Mapiripana', departamento: 'Guainía' },
        { value: 'Morichal', label: 'Morichal', departamento: 'Guainía' },
        { value: 'Pana Pana', label: 'Pana Pana', departamento: 'Guainía' },
        { value: 'Puerto Colombia', label: 'Puerto Colombia', departamento: 'Guainía' },
        { value: 'San Felipe', label: 'San Felipe', departamento: 'Guainía' },
      
        // Guaviare
        { value: 'Calamar', label: 'Calamar', departamento: 'Guaviare' },
        { value: 'El Retorno', label: 'El Retorno', departamento: 'Guaviare' },
        { value: 'Miraflores', label: 'Miraflores', departamento: 'Guaviare' },
        { value: 'San José del Guaviare', label: 'San José del Guaviare', departamento: 'Guaviare' },
      
        // Huila
        { value: 'Acevedo', label: 'Acevedo', departamento: 'Huila' },
        { value: 'Agrado', label: 'Agrado', departamento: 'Huila' },
        { value: 'Aipe', label: 'Aipe', departamento: 'Huila' },
        { value: 'Algeciras', label: 'Algeciras', departamento: 'Huila' },
        { value: 'Altamira', label: 'Altamira', departamento: 'Huila' },
        { value: 'Baraya', label: 'Baraya', departamento: 'Huila' },
        { value: 'Campoalegre', label: 'Campoalegre', departamento: 'Huila' },
        { value: 'Colombia', label: 'Colombia', departamento: 'Huila' },
        { value: 'Elías', label: 'Elías', departamento: 'Huila' },
        { value: 'Garzón', label: 'Garzón', departamento: 'Huila' },
        { value: 'Gigante', label: 'Gigante', departamento: 'Huila' },
        { value: 'Guadalupe', label: 'Guadalupe', departamento: 'Huila' },
        { value: 'Hobo', label: 'Hobo', departamento: 'Huila' },
        { value: 'Íquira', label: 'Íquira', departamento: 'Huila' },
        { value: 'Isnos', label: 'Isnos', departamento: 'Huila' },
        { value: 'La Argentina', label: 'La Argentina', departamento: 'Huila' },
        { value: 'La Plata', label: 'La Plata', departamento: 'Huila' },
        { value: 'Nátaga', label: 'Nátaga', departamento: 'Huila' },
        { value: 'Neiva', label: 'Neiva', departamento: 'Huila' },
        { value: 'Oporapa', label: 'Oporapa', departamento: 'Huila' },
        { value: 'Paicol', label: 'Paicol', departamento: 'Huila' },
        { value: 'Palermo', label: 'Palermo', departamento: 'Huila' },
        { value: 'Palestina', label: 'Palestina', departamento: 'Huila' },
        { value: 'Pital', label: 'Pital', departamento: 'Huila' },
        { value: 'Pitalito', label: 'Pitalito', departamento: 'Huila' },
        { value: 'Rivera', label: 'Rivera', departamento: 'Huila' },
        { value: 'Saladoblanco', label: 'Saladoblanco', departamento: 'Huila' },
        { value: 'San Agustín', label: 'San Agustín', departamento: 'Huila' },
        { value: 'Santa María', label: 'Santa María', departamento: 'Huila' },
        { value: 'Suaza', label: 'Suaza', departamento: 'Huila' },
        { value: 'Tarqui', label: 'Tarqui', departamento: 'Huila' },
        { value: 'Tello', label: 'Tello', departamento: 'Huila' },
        { value: 'Teruel', label: 'Teruel', departamento: 'Huila' },
        { value: 'Tesalia', label: 'Tesalia', departamento: 'Huila' },
        { value: 'Timaná', label: 'Timaná', departamento: 'Huila' },
        { value: 'Villavieja', label: 'Villavieja', departamento: 'Huila' },
        { value: 'Yaguará', label: 'Yaguará', departamento: 'Huila' },
      
        // La Guajira
        { value: 'Albania', label: 'Albania', departamento: 'La Guajira' },
        { value: 'Barrancas', label: 'Barrancas', departamento: 'La Guajira' },
        { value: 'Dibulla', label: 'Dibulla', departamento: 'La Guajira' },
        { value: 'Distracción', label: 'Distracción', departamento: 'La Guajira' },
        { value: 'El Molino', label: 'El Molino', departamento: 'La Guajira' },
        { value: 'Fonseca', label: 'Fonseca', departamento: 'La Guajira' },
        { value: 'Hatonuevo', label: 'Hatonuevo', departamento: 'La Guajira' },
        { value: 'La Jagua del Pilar', label: 'La Jagua del Pilar', departamento: 'La Guajira' },
        { value: 'Maicao', label: 'Maicao', departamento: 'La Guajira' },
        { value: 'Manaure', label: 'Manaure', departamento: 'La Guajira' },
        { value: 'Riohacha', label: 'Riohacha', departamento: 'La Guajira' },
        { value: 'San Juan del Cesar', label: 'San Juan del Cesar', departamento: 'La Guajira' },
        { value: 'Uribia', label: 'Uribia', departamento: 'La Guajira' },
        { value: 'Urumita', label: 'Urumita', departamento: 'La Guajira' },
        { value: 'Villanueva', label: 'Villanueva', departamento: 'La Guajira' },
      
        // Magdalena
        { value: 'Algarrobo', label: 'Algarrobo', departamento: 'Magdalena' },
        { value: 'Aracataca', label: 'Aracataca', departamento: 'Magdalena' },
        { value: 'Ariguaní', label: 'Ariguaní', departamento: 'Magdalena' },
        { value: 'Cerro de San Antonio', label: 'Cerro de San Antonio', departamento: 'Magdalena' },
        { value: 'Chibolo', label: 'Chibolo', departamento: 'Magdalena' },
        { value: 'Ciénaga', label: 'Ciénaga', departamento: 'Magdalena' },
        { value: 'Concordia', label: 'Concordia', departamento: 'Magdalena' },
        { value: 'El Banco', label: 'El Banco', departamento: 'Magdalena' },
        { value: 'El Piñón', label: 'El Piñón', departamento: 'Magdalena' },
        { value: 'El Retén', label: 'El Retén', departamento: 'Magdalena' },
        { value: 'Fundación', label: 'Fundación', departamento: 'Magdalena' },
        { value: 'Guamal', label: 'Guamal', departamento: 'Magdalena' },
        { value: 'Nueva Granada', label: 'Nueva Granada', departamento: 'Magdalena' },
        { value: 'Pedraza', label: 'Pedraza', departamento: 'Magdalena' },
        { value: 'Pijiño del Carmen', label: 'Pijiño del Carmen', departamento: 'Magdalena' },
        { value: 'Pivijay', label: 'Pivijay', departamento: 'Magdalena' },
        { value: 'Plato', label: 'Plato', departamento: 'Magdalena' },
        { value: 'Puebloviejo', label: 'Puebloviejo', departamento: 'Magdalena' },
        { value: 'Remolino', label: 'Remolino', departamento: 'Magdalena' },
        { value: 'Sabanas de San Ángel', label: 'Sabanas de San Ángel', departamento: 'Magdalena' },
        { value: 'Salamina', label: 'Salamina', departamento: 'Magdalena' },
        { value: 'San Sebastián de Buenavista', label: 'San Sebastián de Buenavista', departamento: 'Magdalena' },
        { value: 'San Zenón', label: 'San Zenón', departamento: 'Magdalena' },
        { value: 'Santa Ana', label: 'Santa Ana', departamento: 'Magdalena' },
        { value: 'Santa Bárbara de Pinto', label: 'Santa Bárbara de Pinto', departamento: 'Magdalena' },
        { value: 'Santa Marta', label: 'Santa Marta', departamento: 'Magdalena' },
        { value: 'Sitionuevo', label: 'Sitionuevo', departamento: 'Magdalena' },
        { value: 'Tenerife', label: 'Tenerife', departamento: 'Magdalena' },
        { value: 'Zapayán', label: 'Zapayán', departamento: 'Magdalena' },
        { value: 'Zona Bananera', label: 'Zona Bananera', departamento: 'Magdalena' },
      
        // Meta
        { value: 'Acacías', label: 'Acacías', departamento: 'Meta' },
        { value: 'Barranca de Upía', label: 'Barranca de Upía', departamento: 'Meta' },
        { value: 'Cabuyaro', label: 'Cabuyaro', departamento: 'Meta' },
        { value: 'Castilla la Nueva', label: 'Castilla la Nueva', departamento: 'Meta' },
        { value: 'Cubarral', label: 'Cubarral', departamento: 'Meta' },
        { value: 'Cumaral', label: 'Cumaral', departamento: 'Meta' },
        { value: 'El Calvario', label: 'El Calvario', departamento: 'Meta' },
        { value: 'El Castillo', label: 'El Castillo', departamento: 'Meta' },
        { value: 'El Dorado', label: 'El Dorado', departamento: 'Meta' },
        { value: 'Fuente de Oro', label: 'Fuente de Oro', departamento: 'Meta' },
        { value: 'Granada', label: 'Granada', departamento: 'Meta' },
        { value: 'Guamal', label: 'Guamal', departamento: 'Meta' },
        { value: 'La Macarena', label: 'La Macarena', departamento: 'Meta' },
        { value: 'La Uribe', label: 'La Uribe', departamento: 'Meta' },
        { value: 'Lejanías', label: 'Lejanías', departamento: 'Meta' },
        { value: 'Mapiripán', label: 'Mapiripán', departamento: 'Meta' },
        { value: 'Mesetas', label: 'Mesetas', departamento: 'Meta' },
        { value: 'Puerto Concordia', label: 'Puerto Concordia', departamento: 'Meta' },
        { value: 'Puerto Gaitán', label: 'Puerto Gaitán', departamento: 'Meta' },
        { value: 'Puerto Lleras', label: 'Puerto Lleras', departamento: 'Meta' },
        { value: 'Puerto López', label: 'Puerto López', departamento: 'Meta' },
        { value: 'Puerto Rico', label: 'Puerto Rico', departamento: 'Meta' },
        { value: 'Restrepo', label: 'Restrepo', departamento: 'Meta' },
        { value: 'San Carlos de Guaroa', label: 'San Carlos de Guaroa', departamento: 'Meta' },
        { value: 'San Juan de Arama', label: 'San Juan de Arama', departamento: 'Meta' },
        { value: 'San Juanito', label: 'San Juanito', departamento: 'Meta' },
        { value: 'San Martín', label: 'San Martín', departamento: 'Meta' },
        { value: 'Villavicencio', label: 'Villavicencio', departamento: 'Meta' },
        { value: 'Vista Hermosa', label: 'Vista Hermosa', departamento: 'Meta' },
      
        // Nariño
        { value: 'Aldana', label: 'Aldana', departamento: 'Nariño' },
        { value: 'Ancuyá', label: 'Ancuyá', departamento: 'Nariño' },
        { value: 'Arboleda', label: 'Arboleda', departamento: 'Nariño' },
        { value: 'Barbacoas', label: 'Barbacoas', departamento: 'Nariño' },
        { value: 'Belén', label: 'Belén', departamento: 'Nariño' },
        { value: 'Buesaco', label: 'Buesaco', departamento: 'Nariño' },
        { value: 'Chachagüí', label: 'Chachagüí', departamento: 'Nariño' },
        { value: 'Colón', label: 'Colón', departamento: 'Nariño' },
        { value: 'Consacá', label: 'Consacá', departamento: 'Nariño' },
        { value: 'Contadero', label: 'Contadero', departamento: 'Nariño' },
        { value: 'Córdoba', label: 'Córdoba', departamento: 'Nariño' },
        { value: 'Cuaspud', label: 'Cuaspud', departamento: 'Nariño' },
        { value: 'Cumbal', label: 'Cumbal', departamento: 'Nariño' },
        { value: 'Cumbitara', label: 'Cumbitara', departamento: 'Nariño' },
        { value: 'El Charco', label: 'El Charco', departamento: 'Nariño' },
        { value: 'El Peñol', label: 'El Peñol', departamento: 'Nariño' },
        { value: 'El Rosario', label: 'El Rosario', departamento: 'Nariño' },
        { value: 'El Tablón de Gómez', label: 'El Tablón de Gómez', departamento: 'Nariño' },
        { value: 'El Tambo', label: 'El Tambo', departamento: 'Nariño' },
        { value: 'Francisco Pizarro', label: 'Francisco Pizarro', departamento: 'Nariño' },
        { value: 'Funes', label: 'Funes', departamento: 'Nariño' },
        { value: 'Guachucal', label: 'Guachucal', departamento: 'Nariño' },
        { value: 'Guaitarilla', label: 'Guaitarilla', departamento: 'Nariño' },
        { value: 'Gualmatán', label: 'Gualmatán', departamento: 'Nariño' },
        { value: 'Iles', label: 'Iles', departamento: 'Nariño' },
        { value: 'Imués', label: 'Imués', departamento: 'Nariño' },
        { value: 'Ipiales', label: 'Ipiales', departamento: 'Nariño' },
        { value: 'La Cruz', label: 'La Cruz', departamento: 'Nariño' },
        { value: 'La Florida', label: 'La Florida', departamento: 'Nariño' },
        { value: 'La Llanada', label: 'La Llanada', departamento: 'Nariño' },
        { value: 'La Tola', label: 'La Tola', departamento: 'Nariño' },
        { value: 'La Unión', label: 'La Unión', departamento: 'Nariño' },
        { value: 'Leiva', label: 'Leiva', departamento: 'Nariño' },
        { value: 'Linares', label: 'Linares', departamento: 'Nariño' },
        { value: 'Los Andes', label: 'Los Andes', departamento: 'Nariño' },
        { value: 'Magüí', label: 'Magüí', departamento: 'Nariño' },
        { value: 'Mallama', label: 'Mallama', departamento: 'Nariño' },
        { value: 'Mosquera', label: 'Mosquera', departamento: 'Nariño' },
        { value: 'Nariño', label: 'Nariño', departamento: 'Nariño' },
        { value: 'Olaya Herrera', label: 'Olaya Herrera', departamento: 'Nariño' },
        { value: 'Ospina', label: 'Ospina', departamento: 'Nariño' },
        { value: 'Pasto', label: 'Pasto', departamento: 'Nariño' },
        { value: 'Policarpa', label: 'Policarpa', departamento: 'Nariño' },
        { value: 'Potosí', label: 'Potosí', departamento: 'Nariño' },
        { value: 'Providencia', label: 'Providencia', departamento: 'Nariño' },
        { value: 'Puerres', label: 'Puerres', departamento: 'Nariño' },
        { value: 'Pupiales', label: 'Pupiales', departamento: 'Nariño' },
        { value: 'Ricaurte', label: 'Ricaurte', departamento: 'Nariño' },
        { value: 'Roberto Payán', label: 'Roberto Payán', departamento: 'Nariño' },
        { value: 'Samaniego', label: 'Samaniego', departamento: 'Nariño' },
        { value: 'San Bernardo', label: 'San Bernardo', departamento: 'Nariño' },
        { value: 'San Lorenzo', label: 'San Lorenzo', departamento: 'Nariño' },
        { value: 'San Pablo', label: 'San Pablo', departamento: 'Nariño' },
        { value: 'San Pedro de Cartago', label: 'San Pedro de Cartago', departamento: 'Nariño' },
        { value: 'Sandoná', label: 'Sandoná', departamento: 'Nariño' },
        { value: 'Santa Bárbara', label: 'Santa Bárbara', departamento: 'Nariño' },
        { value: 'Santacruz', label: 'Santacruz', departamento: 'Nariño' },
        { value: 'Sapuyes', label: 'Sapuyes', departamento: 'Nariño' },
        { value: 'Taminango', label: 'Taminango', departamento: 'Nariño' },
        { value: 'Tangua', label: 'Tangua', departamento: 'Nariño' },
        { value: 'Túquerres', label: 'Túquerres', departamento: 'Nariño' },
        { value: 'Yacuanquer', label: 'Yacuanquer', departamento: 'Nariño' },
      
        // Norte de Santander
        { value: 'Ábrego', label: 'Ábrego', departamento: 'Norte de Santander' },
        { value: 'Arboledas', label: 'Arboledas', departamento: 'Norte de Santander' },
        { value: 'Bochalema', label: 'Bochalema', departamento: 'Norte de Santander' },
        { value: 'Bucarasica', label: 'Bucarasica', departamento: 'Norte de Santander' },
        { value: 'Cáchira', label: 'Cáchira', departamento: 'Norte de Santander' },
        { value: 'Cácota', label: 'Cácota', departamento: 'Norte de Santander' },
        { value: 'Chinácota', label: 'Chinácota', departamento: 'Norte de Santander' },
        { value: 'Chitagá', label: 'Chitagá', departamento: 'Norte de Santander' },
        { value: 'Convención', label: 'Convención', departamento: 'Norte de Santander' },
        { value: 'Cúcuta', label: 'Cúcuta', departamento: 'Norte de Santander' },
        { value: 'Cucutilla', label: 'Cucutilla', departamento: 'Norte de Santander' },
        { value: 'Durania', label: 'Durania', departamento: 'Norte de Santander' },
        { value: 'El Carmen', label: 'El Carmen', departamento: 'Norte de Santander' },
        { value: 'El Tarra', label: 'El Tarra', departamento: 'Norte de Santander' },
        { value: 'El Zulia', label: 'El Zulia', departamento: 'Norte de Santander' },
        { value: 'Gramalote', label: 'Gramalote', departamento: 'Norte de Santander' },
        { value: 'Hacarí', label: 'Hacarí', departamento: 'Norte de Santander' },
        { value: 'Herrán', label: 'Herrán', departamento: 'Norte de Santander' },
        { value: 'La Esperanza', label: 'La Esperanza', departamento: 'Norte de Santander' },
        { value: 'La Playa', label: 'La Playa', departamento: 'Norte de Santander' },
        { value: 'Labateca', label: 'Labateca', departamento: 'Norte de Santander' },
        { value: 'Los Patios', label: 'Los Patios', departamento: 'Norte de Santander' },
        { value: 'Lourdes', label: 'Lourdes', departamento: 'Norte de Santander' },
        { value: 'Mutiscua', label: 'Mutiscua', departamento: 'Norte de Santander' },
        { value: 'Ocaña', label: 'Ocaña', departamento: 'Norte de Santander' },
        { value: 'Pamplona', label: 'Pamplona', departamento: 'Norte de Santander' },
        { value: 'Pamplonita', label: 'Pamplonita', departamento: 'Norte de Santander' },
        { value: 'Puerto Santander', label: 'Puerto Santander', departamento: 'Norte de Santander' },
        { value: 'Ragonvalia', label: 'Ragonvalia', departamento: 'Norte de Santander' },
        { value: 'Salazar', label: 'Salazar', departamento: 'Norte de Santander' },
        { value: 'San Calixto', label: 'San Calixto', departamento: 'Norte de Santander' },
        { value: 'San Cayetano', label: 'San Cayetano', departamento: 'Norte de Santander' },
        { value: 'Santiago', label: 'Santiago', departamento: 'Norte de Santander' },
        { value: 'Santo Domingo de Silos', label: 'Santo Domingo de Silos', departamento: 'Norte de Santander' },
        { value: 'Sardinata', label: 'Sardinata', departamento: 'Norte de Santander' },
        { value: 'Teorama', label: 'Teorama', departamento: 'Norte de Santander' },
        { value: 'Tibú', label: 'Tibú', departamento: 'Norte de Santander' },
        { value: 'Toledo', label: 'Toledo', departamento: 'Norte de Santander' },
        { value: 'Villa Caro', label: 'Villa Caro', departamento: 'Norte de Santander' },
        { value: 'Villa del Rosario', label: 'Villa del Rosario', departamento: 'Norte de Santander' },
      
        // Putumayo
        { value: 'Colón', label: 'Colón', departamento: 'Putumayo' },
        { value: 'Mocoa', label: 'Mocoa', departamento: 'Putumayo' },
        { value: 'Orito', label: 'Orito', departamento: 'Putumayo' },
        { value: 'Puerto Asís', label: 'Puerto Asís', departamento: 'Putumayo' },
        { value: 'Puerto Caicedo', label: 'Puerto Caicedo', departamento: 'Putumayo' },
        { value: 'Puerto Guzmán', label: 'Puerto Guzmán', departamento: 'Putumayo' },
        { value: 'Puerto Leguízamo', label: 'Puerto Leguízamo', departamento: 'Putumayo' },
        { value: 'San Francisco', label: 'San Francisco', departamento: 'Putumayo' },
        { value: 'San Miguel', label: 'San Miguel', departamento: 'Putumayo' },
        { value: 'Santiago', label: 'Santiago', departamento: 'Putumayo' },
        { value: 'Sibundoy', label: 'Sibundoy', departamento: 'Putumayo' },
        { value: 'Valle del Guamuez', label: 'Valle del Guamuez', departamento: 'Putumayo' },
        { value: 'Villagarzón', label: 'Villagarzón', departamento: 'Putumayo' },
      
        // Quindío
        { value: 'Armenia', label: 'Armenia', departamento: 'Quindío' },
        { value: 'Buenavista', label: 'Buenavista', departamento: 'Quindío' },
        { value: 'Calarcá', label: 'Calarcá', departamento: 'Quindío' },
        { value: 'Circasia', label: 'Circasia', departamento: 'Quindío' },
        { value: 'Córdoba', label: 'Córdoba', departamento: 'Quindío' },
        { value: 'Filandia', label: 'Filandia', departamento: 'Quindío' },
        { value: 'Génova', label: 'Génova', departamento: 'Quindío' },
        { value: 'La Tebaida', label: 'La Tebaida', departamento: 'Quindío' },
        { value: 'Montenegro', label: 'Montenegro', departamento: 'Quindío' },
        { value: 'Pijao', label: 'Pijao', departamento: 'Quindío' },
        { value: 'Quimbaya', label: 'Quimbaya', departamento: 'Quindío' },
        { value: 'Salento', label: 'Salento', departamento: 'Quindío' },
      
        // Risaralda
        { value: 'Apía', label: 'Apía', departamento: 'Risaralda' },
        { value: 'Balboa', label: 'Balboa', departamento: 'Risaralda' },
        { value: 'Belén de Umbría', label: 'Belén de Umbría', departamento: 'Risaralda' },
        { value: 'Dosquebradas', label: 'Dosquebradas', departamento: 'Risaralda' },
        { value: 'Guática', label: 'Guática', departamento: 'Risaralda' },
        { value: 'La Celia', label: 'La Celia', departamento: 'Risaralda' },
        { value: 'La Virginia', label: 'La Virginia', departamento: 'Risaralda' },
        { value: 'Marsella', label: 'Marsella', departamento: 'Risaralda' },
        { value: 'Mistrató', label: 'Mistrató', departamento: 'Risaralda' },
        { value: 'Pereira', label: 'Pereira', departamento: 'Risaralda' },
        { value: 'Pueblo Rico', label: 'Pueblo Rico', departamento: 'Risaralda' },
        { value: 'Quinchía', label: 'Quinchía', departamento: 'Risaralda' },
        { value: 'Santa Rosa de Cabal', label: 'Santa Rosa de Cabal', departamento: 'Risaralda' },
        { value: 'Santuario', label: 'Santuario', departamento: 'Risaralda' },
      
        // San Andrés y Providencia
        { value: 'Providencia', label: 'Providencia', departamento: 'San Andrés y Providencia' },
        { value: 'San Andrés', label: 'San Andrés', departamento: 'San Andrés y Providencia' },
        { value: 'Aguada', label: 'Aguada', departamento: 'Santander' },
        { value: 'Albania', label: 'Albania', departamento: 'Santander' },
        { value: 'Aratoca', label: 'Aratoca', departamento: 'Santander' },
        { value: 'Barbosa', label: 'Barbosa', departamento: 'Santander' },
        { value: 'Barichara', label: 'Barichara', departamento: 'Santander' },
        { value: 'Barrancabermeja', label: 'Barrancabermeja', departamento: 'Santander' },
        { value: 'Betulia', label: 'Betulia', departamento: 'Santander' },
        { value: 'Bolívar', label: 'Bolívar', departamento: 'Santander' },
        { value: 'Bucaramanga', label: 'Bucaramanga', departamento: 'Santander' },
        { value: 'Cabrera', label: 'Cabrera', departamento: 'Santander' },
        { value: 'California', label: 'California', departamento: 'Santander' },
        { value: 'Capitanejo', label: 'Capitanejo', departamento: 'Santander' },
        { value: 'Carcasí', label: 'Carcasí', departamento: 'Santander' },
        { value: 'Cepitá', label: 'Cepitá', departamento: 'Santander' },
        { value: 'Cerrito', label: 'Cerrito', departamento: 'Santander' },
        { value: 'Charalá', label: 'Charalá', departamento: 'Santander' },
        { value: 'Charta', label: 'Charta', departamento: 'Santander' },
        { value: 'Chima', label: 'Chima', departamento: 'Santander' },
        { value: 'Chipatá', label: 'Chipatá', departamento: 'Santander' },
        { value: 'Cimitarra', label: 'Cimitarra', departamento: 'Santander' },
        { value: 'Concepción', label: 'Concepción', departamento: 'Santander' },
        { value: 'Confines', label: 'Confines', departamento: 'Santander' },
        { value: 'Contratación', label: 'Contratación', departamento: 'Santander' },
        { value: 'Coromoro', label: 'Coromoro', departamento: 'Santander' },
        { value: 'Curití', label: 'Curití', departamento: 'Santander' },
        { value: 'El Carmen de Chucurí', label: 'El Carmen de Chucurí', departamento: 'Santander' },
        { value: 'El Guacamayo', label: 'El Guacamayo', departamento: 'Santander' },
        { value: 'El Peñón', label: 'El Peñón', departamento: 'Santander' },
        { value: 'El Playón', label: 'El Playón', departamento: 'Santander' },
        { value: 'Encino', label: 'Encino', departamento: 'Santander' },
        { value: 'Enciso', label: 'Enciso', departamento: 'Santander' },
        { value: 'Florián', label: 'Florián', departamento: 'Santander' },
        { value: 'Floridablanca', label: 'Floridablanca', departamento: 'Santander' },
        { value: 'Galán', label: 'Galán', departamento: 'Santander' },
        { value: 'Gámbita', label: 'Gámbita', departamento: 'Santander' },
        { value: 'Girón', label: 'Girón', departamento: 'Santander' },
        { value: 'Guaca', label: 'Guaca', departamento: 'Santander' },
        { value: 'Guadalupe', label: 'Guadalupe', departamento: 'Santander' },
        { value: 'Guapotá', label: 'Guapotá', departamento: 'Santander' },
        { value: 'Guavatá', label: 'Guavatá', departamento: 'Santander' },
        { value: 'Güepsa', label: 'Güepsa', departamento: 'Santander' },
        { value: 'Hato', label: 'Hato', departamento: 'Santander' },
        { value: 'Jesús María', label: 'Jesús María', departamento: 'Santander' },
        { value: 'Jordán', label: 'Jordán', departamento: 'Santander' },
        { value: 'La Belleza', label: 'La Belleza', departamento: 'Santander' },
        { value: 'La Paz', label: 'La Paz', departamento: 'Santander' },
        { value: 'Landázuri', label: 'Landázuri', departamento: 'Santander' },
        { value: 'Lebrija', label: 'Lebrija', departamento: 'Santander' },
        { value: 'Los Santos', label: 'Los Santos', departamento: 'Santander' },
        { value: 'Macaravita', label: 'Macaravita', departamento: 'Santander' },
        { value: 'Málaga', label: 'Málaga', departamento: 'Santander' },
        { value: 'Matanza', label: 'Matanza', departamento: 'Santander' },
        { value: 'Mogotes', label: 'Mogotes', departamento: 'Santander' },
        { value: 'Molagavita', label: 'Molagavita', departamento: 'Santander' },
        { value: 'Ocamonte', label: 'Ocamonte', departamento: 'Santander' },
        { value: 'Oiba', label: 'Oiba', departamento: 'Santander' },
        { value: 'Onzaga', label: 'Onzaga', departamento: 'Santander' },
        { value: 'Palmas del Socorro', label: 'Palmas del Socorro', departamento: 'Santander' },
        { value: 'Páramo', label: 'Páramo', departamento: 'Santander' },
        { value: 'Piedecuesta', label: 'Piedecuesta', departamento: 'Santander' },
        { value: 'Pinchote', label: 'Pinchote', departamento: 'Santander' },
        { value: 'Puente Nacional', label: 'Puente Nacional', departamento: 'Santander' },
        { value: 'Puerto Parra', label: 'Puerto Parra', departamento: 'Santander' },
        { value: 'Puerto Wilches', label: 'Puerto Wilches', departamento: 'Santander' },
        { value: 'Rionegro', label: 'Rionegro', departamento: 'Santander' },
        { value: 'Sabana de Torres', label: 'Sabana de Torres', departamento: 'Santander' },
        { value: 'San Andrés', label: 'San Andrés', departamento: 'Santander' },
        { value: 'San Benito', label: 'San Benito', departamento: 'Santander' },
        { value: 'San Gil', label: 'San Gil', departamento: 'Santander' },
        { value: 'San Joaquín', label: 'San Joaquín', departamento: 'Santander' },
        { value: 'San José de Miranda', label: 'San José de Miranda', departamento: 'Santander' },
        { value: 'San Miguel', label: 'San Miguel', departamento: 'Santander' },
        { value: 'San Vicente de Chucurí', label: 'San Vicente de Chucurí', departamento: 'Santander' },
        { value: 'Santa Bárbara', label: 'Santa Bárbara', departamento: 'Santander' },
        { value: 'Santa Helena del Opón', label: 'Santa Helena del Opón', departamento: 'Santander' },
        { value: 'Simacota', label: 'Simacota', departamento: 'Santander' },
        { value: 'Socorro', label: 'Socorro', departamento: 'Santander' },
        { value: 'Suaita', label: 'Suaita', departamento: 'Santander' },
        { value: 'Sucre', label: 'Sucre', departamento: 'Santander' },
        { value: 'Suratá', label: 'Suratá', departamento: 'Santander' },
        { value: 'Tona', label: 'Tona', departamento: 'Santander' },
        { value: 'Valle de San José', label: 'Valle de San José', departamento: 'Santander' },
        { value: 'Vélez', label: 'Vélez', departamento: 'Santander' },
        { value: 'Vetas', label: 'Vetas', departamento: 'Santander' },
        { value: 'Villanueva', label: 'Villanueva', departamento: 'Santander' },
        { value: 'Zapatoca', label: 'Zapatoca', departamento: 'Santander' },
        { value: 'Buenavista', label: 'Buenavista', departamento: 'Sucre' },
        { value: 'Caimito', label: 'Caimito', departamento: 'Sucre' },
        { value: 'Chalán', label: 'Chalán', departamento: 'Sucre' },
        { value: 'Colosó', label: 'Colosó', departamento: 'Sucre' },
        { value: 'Corozal', label: 'Corozal', departamento: 'Sucre' },
        { value: 'Coveñas', label: 'Coveñas', departamento: 'Sucre' },
        { value: 'El Roble', label: 'El Roble', departamento: 'Sucre' },
        { value: 'Galeras', label: 'Galeras', departamento: 'Sucre' },
        { value: 'Guaranda', label: 'Guaranda', departamento: 'Sucre' },
        { value: 'La Unión', label: 'La Unión', departamento: 'Sucre' },
        { value: 'Los Palmitos', label: 'Los Palmitos', departamento: 'Sucre' },
        { value: 'Majagual', label: 'Majagual', departamento: 'Sucre' },
        { value: 'Morroa', label: 'Morroa', departamento: 'Sucre' },
        { value: 'Ovejas', label: 'Ovejas', departamento: 'Sucre' },
        { value: 'Palmito', label: 'Palmito', departamento: 'Sucre' },
        { value: 'Sampués', label: 'Sampués', departamento: 'Sucre' },
        { value: 'San Benito Abad', label: 'San Benito Abad', departamento: 'Sucre' },
        { value: 'San Juan de Betulia', label: 'San Juan de Betulia', departamento: 'Sucre' },
        { value: 'San Marcos', label: 'San Marcos', departamento: 'Sucre' },
        { value: 'San Onofre', label: 'San Onofre', departamento: 'Sucre' },
        { value: 'San Pedro', label: 'San Pedro', departamento: 'Sucre' },
        { value: 'Santiago de Tolú', label: 'Santiago de Tolú', departamento: 'Sucre' },
        { value: 'Sincelejo', label: 'Sincelejo', departamento: 'Sucre' },
        { value: 'Sincé', label: 'Sincé', departamento: 'Sucre' },
        { value: 'Sucre', label: 'Sucre', departamento: 'Sucre' },
        { value: 'Tolú Viejo', label: 'Tolú Viejo', departamento: 'Sucre' },
        { value: 'Alpujarra', label: 'Alpujarra', departamento: 'Tolima' },
        { value: 'Alvarado', label: 'Alvarado', departamento: 'Tolima' },
        { value: 'Ambalema', label: 'Ambalema', departamento: 'Tolima' },
        { value: 'Anzoátegui', label: 'Anzoátegui', departamento: 'Tolima' },
        { value: 'Armero', label: 'Armero', departamento: 'Tolima' },
        { value: 'Ataco', label: 'Ataco', departamento: 'Tolima' },
        { value: 'Cajamarca', label: 'Cajamarca', departamento: 'Tolima' },
        { value: 'Carmen de Apicalá', label: 'Carmen de Apicalá', departamento: 'Tolima' },
        { value: 'Casabianca', label: 'Casabianca', departamento: 'Tolima' },
        { value: 'Chaparral', label: 'Chaparral', departamento: 'Tolima' },
        { value: 'Coello', label: 'Coello', departamento: 'Tolima' },
        { value: 'Coyaima', label: 'Coyaima', departamento: 'Tolima' },
        { value: 'Cunday', label: 'Cunday', departamento: 'Tolima' },
        { value: 'Dolores', label: 'Dolores', departamento: 'Tolima' },
        { value: 'Espinal', label: 'Espinal', departamento: 'Tolima' },
        { value: 'Falan', label: 'Falan', departamento: 'Tolima' },
        { value: 'Flandes', label: 'Flandes', departamento: 'Tolima' },
        { value: 'Fresno', label: 'Fresno', departamento: 'Tolima' },
        { value: 'Guamo', label: 'Guamo', departamento: 'Tolima' },
        { value: 'Herveo', label: 'Herveo', departamento: 'Tolima' },
        { value: 'Honda', label: 'Honda', departamento: 'Tolima' },
        { value: 'Ibagué', label: 'Ibagué', departamento: 'Tolima' },
        { value: 'Icononzo', label: 'Icononzo', departamento: 'Tolima' },
        { value: 'Lérida', label: 'Lérida', departamento: 'Tolima' },
        { value: 'Líbano',label: 'Líbano',  departamento: 'Tolima' },
        { value: 'Mariquita', label: 'Mariquita', departamento: 'Tolima' },
        { value: 'Melgar', label: 'Melgar', departamento: 'Tolima' },
        { value: 'Murillo', label: 'Murillo', departamento: 'Tolima' },
        { value: 'Natagaima', label: 'Natagaima', departamento: 'Tolima' },
        { value: 'Ortega', label: 'Ortega', departamento: 'Tolima' },
        { value: 'Palocabildo', label: 'Palocabildo', departamento: 'Tolima' },
        { value: 'Piedras', label: 'Piedras', departamento: 'Tolima' },
        { value: 'Planadas', label: 'Planadas', departamento: 'Tolima' },
        { value: 'Prado', label: 'Prado', departamento: 'Tolima' },
        { value: 'Purificación', label: 'Purificación', departamento: 'Tolima' },
        { value: 'Rioblanco', label: 'Rioblanco', departamento: 'Tolima' },
        { value: 'Roncesvalles', label: 'Roncesvalles', departamento: 'Tolima' },
        { value: 'Rovira', label: 'Rovira', departamento: 'Tolima' },
        { value: 'Saldaña', label: 'Saldaña', departamento: 'Tolima' },
        { value: 'San Antonio', label: 'San Antonio', departamento: 'Tolima' },
        { value: 'San Luis', label: 'San Luis', departamento: 'Tolima' },
        { value: 'Santa Isabel', label: 'Santa Isabel', departamento: 'Tolima' },
        { value: 'Venadillo', label: 'Venadillo', departamento: 'Tolima' },
        { value: 'Villahermosa', label: 'Villahermosa', departamento: 'Tolima' },
        { value: 'Villarrica', label: 'Villarrica', departamento: 'Tolima' },
        { value: 'Alpujarra', label: 'Alpujarra', departamento: 'Tolima' },
        { value: 'Alvarado', label: 'Alvarado', departamento: 'Tolima' },
        { value: 'Ambalema', label: 'Ambalema', departamento: 'Tolima' },
        { value: 'Anzoátegui', label: 'Anzoátegui', departamento: 'Tolima' },
        { value: 'Armero', label: 'Armero', departamento: 'Tolima' },
        { value: 'Ataco', label: 'Ataco', departamento: 'Tolima' },
        { value: 'Cajamarca', label: 'Cajamarca', departamento: 'Tolima' },
        { value: 'Carmen de Apicalá', label: 'Carmen de Apicalá', departamento: 'Tolima' },
        { value: 'Casabianca', label: 'Casabianca', departamento: 'Tolima' },
        { value: 'Chaparral', label: 'Chaparral', departamento: 'Tolima' },
        { value: 'Coello', label: 'Coello', departamento: 'Tolima' },
        { value: 'Coyaima', label: 'Coyaima', departamento: 'Tolima' },
        { value: 'Cunday', label: 'Cunday', departamento: 'Tolima' },
        { value: 'Dolores', label: 'Dolores', departamento: 'Tolima' },
        { value: 'Espinal', label: 'Espinal', departamento: 'Tolima' },
        { value: 'Falan', label: 'Falan', departamento: 'Tolima' },
        { value: 'Flandes', label: 'Flandes', departamento: 'Tolima' },
        { value: 'Fresno', label: 'Fresno', departamento: 'Tolima' },
        { value: 'Guamo', label: 'Guamo', departamento: 'Tolima' },
        { value: 'Herveo', label: 'Herveo', departamento: 'Tolima' },
        { value: 'Honda', label: 'Honda', departamento: 'Tolima' },
        { value: 'Ibagué', label: 'Ibagué', departamento: 'Tolima' },
        { value: 'Icononzo', label: 'Icononzo', departamento: 'Tolima' },
        { value: 'Lérida', label: 'Lérida', departamento: 'Tolima' },
        { value: 'Líbano', label: 'Líbano', departamento: 'Tolima' },
        { value: 'Mariquita', label: 'Mariquita', departamento: 'Tolima' },
        { value: 'Melgar', label: 'Melgar', departamento: 'Tolima' },
        { value: 'Murillo', label: 'Murillo', departamento: 'Tolima' },
        { value: 'Natagaima', label: 'Natagaima', departamento: 'Tolima' },
        { value: 'Ortega', label: 'Ortega', departamento: 'Tolima' },
        { value: 'Palocabildo', label: 'Palocabildo', departamento: 'Tolima' },
        { value: 'Piedras', label: 'Piedras', departamento: 'Tolima' },
        { value: 'Planadas', label: 'Planadas', departamento: 'Tolima' },
        { value: 'Prado', label: 'Prado', departamento: 'Tolima' },
        { value: 'Purificación', label: 'Purificación', departamento: 'Tolima' },
        { value: 'Rioblanco', label: 'Rioblanco', departamento: 'Tolima' },
        { value: 'Roncesvalles', label: 'Roncesvalles', departamento: 'Tolima' },
        { value: 'Rovira', label: 'Rovira', departamento: 'Tolima' },
        { value: 'Saldaña', label: 'Saldaña', departamento: 'Tolima' },
        { value: 'San Antonio', label: 'San Antonio', departamento: 'Tolima' },
        { value: 'San Luis', label: 'San Luis', departamento: 'Tolima' },
        { value: 'Santa Isabel', label: 'Santa Isabel', departamento: 'Tolima' },
        { value: 'Venadillo', label: 'Venadillo', departamento: 'Tolima' },
        { value: 'Villahermosa', label: 'Villahermosa', departamento: 'Tolima' },
        { value: 'Villarrica', label: 'Villarrica', departamento: 'Tolima' },
        { value: 'Carurú', label: 'Carurú', departamento: 'Vaupés' },
        { value: 'Mitú', label: 'Mitú', departamento: 'Vaupés' },
        { value: 'Papunaua', label: 'Papunaua', departamento: 'Vaupés' },
        { value: 'Taraira', label: 'Taraira', departamento: 'Vaupés' },
        { value: 'Yavaraté', label: 'Yavaraté', departamento: 'Vaupés' },    
        { value: 'Cumaribo', label: 'Cumaribo', departamento: 'Vichada' },
        { value: 'La Primavera', label: 'La Primavera', departamento: 'Vichada' },
        { value: 'Puerto Carreño', label: 'Puerto Carreño', departamento: 'Vichada' },
        { value: 'Santa Rosalía', label: 'Santa Rosalía', departamento: 'Vichada' },   
    
  ];
  export default municipios;