const config = {
	 
    API_URL_WEB: "https://www.lacasadelbarbero.com.co/",
    API_URL: "https://www.lacasadelbarbero.com.co/api2024/apiv1/?",
   // API_URL: "https://www.lacasadelbarbero.com.co/api2024/plugins-dist/api2025/?",
	API_URL_AUTH : '/dashboard/tarjetas', 
	API_ACCION_AUTH  :  'auteur', 
	API_OPCION_AUTH  : 'login', 
	API_URL_USUARIOS: '/administrador/usuarios', 
    API_URL_ROLES: '/administrador/Roles', 
	 
	API_OPCION_CONSULTA_ROLES:'consulta_roles',
	API_OPCION_EDITAR_ROLES:'editar_roles',
	API_OPCION_ADD_ROLES:'add_roles',
	API_OPCION_DELETE_ROLES:'delete_roles',
	API_ACCION_ROLES:'roles',

	API_ACCION_USUARIOS:'usuarios',
	API_OPCION_CONSULTA_USUARIOS:'consulta',
	API_OPCION_ADD_USUARIOS:'guardar',
	API_OPCION_EDITAR_USUARIOS:'update',
	API_OPCION_DELETE_USUARIOS:'delete',
	
	API_IMPORTAR_PREGUNTAS_MODELO_2:'guardar_evaluacion_modelo_2',
	API_URL_ADMISIONES:'admisiones/CargaAcademica',
	API_URL_CUESTION_ASPIRANTES:'cuestionarios/CuestionarioAspirante',
	API_URL_CUESTIONARIOS:'cuestionarios/',
	API_ACCION_ADMISIONES:'cargacademica',
	API_ACCION_EVALUACIONES_ASPIRANTES:'prueba_aspirantes',
	API_OPCION_CONSULTAR_PRUEBA_ASPIRANTE:'consulta_prueba_aspirante',
	API_OPCION_CONSULTA_ESTUDIANTES:'consulta_estudiantes',
	API_ESTUDIANTES_IMPORTAR:'importar_estudiantes',
	API_OPCION_INSCRIPCIONES:'inscripciones',
	API_OPCION_REGISTAR_PRUEBA:'registrar_prueba',
	API_OPCION_CONSULTAR_DOCUMENTO:'consultar_documento',
	API_OPCION_REGISTAR_OPORTUNIDADES:'regitrar_oportunidades',
	API_OPCION_MARCAR_OPORTUNIDADES:'marcar_oportunidades',
	API_OPCION_EDITAR_PREGUNTA:'editar_pregunta',
	API_OPCION_UPDATE_EVALUACION_PREGUNTA:'update_evaluacion_pregunta',
	API_OPCION_CONSULTA_ID_PREGUNTA:'consulta_id_pregunta',
	API_OPCION_EDITAR_RESPUESTA:'editar_respuesta',
	API_OPCION_CONSULTA_ID_RESPUESTAS:'consulta_id_respuestas',
	API_OPCION_CONSULTA_BLOQUE_SECC_ASIG_BITAC:'guardar_bloque_seccion_asig_bitacora',
	API_OPCION_CONSULTA_SECCIONES:'consultar_seccion',
	API_GUARDAR_SECCION:'guardar_seccion',
	API_OPCION_GUARDAR_RESPUESTAS:'guardar_respuesta',
	API_OPCION_ELIMINAR_PREGUNTA:'eliminar_pregunta',
	API_OPCION_CONSULTA_PREGUNTAS:'consulta_preguntas',
	API_GUARDAR_PREGUNTA:'guardar_pregunta', 
	API_OPCION_ADD_EVALUACION:'add_evaluacion',
	API_OPCION_UPDATE_EVALUACION:'update_evaluacion',  
	API_OPCION_CONSULTAR_EVALUACION:'consulta_evaluacion',
	API_OPCION_DELETE_EVALUACION: 'delete_evaluacion', 
	API_OPCION_ACTUALIZA_PASS  :  'actualizapass', 
	API_ACCION_NOMINA  :  'nominas', 
	API_ACCION_NOVEDADES  :  'novedades', 
	API_ACCION_INSCRIPCIONES: 'inscripciones', 
	API_OPCION_EVALUACIONES: 'Evaluaciones', 
	API_URL_EVALUACIONES: 'Evaluaciones', 
	API_OPCION_IMPORTAR:'importar',
	API_OPCION_GUARDAR  : 'guardar', 
	API_OPCION_GUARDAR_CHECKOUT  : 'guardar_checkout', 
	API_OPCION_CONSULTA  : 'consulta', 

	API_OPCION_CONSULTA_COMPLETA  : 'consulta_completa', 
	API_OPCION_CONSULTA_ID  : 'consultaId', 
	API_OPCION_DELETE  : 'delete', 
	API_OPCION_ADD  : 'delete', 
	API_OPCION_UPDATE  : 'update', 
	X_SICES_API_APIKEY:'zHqroBk5BILvT9Bdajol1A==::snR8ET+DxazKVH5Ywxx1Fg==',
	X_SICES_API_APITOKEN:'f37ef65fbc641054a3b508af0b52220916ff40eefa9a0a722b4d69cda96ef064',

	X_SICES_API_APIKEY_USER:'U9YbCFRmbhm9GjlHTAuKvgipgvku1ljhR9YbTkpMNtXmhMa/tsvlZS2eCOtGqe94vNJ+QDtM23pRQxRytrZR3TtXyPbozsxT4q0E/z/hY5o=::1hFXGPLErNPJxf8FuXdeLA==',
	X_SICES_API_APITOKEN_USER:'1eddeff45f94f4ab39b8c1f0ee840ed296b606608c3af799787f2dafa9e64320',
	X_SICES_API_USER:'C07B51296CED3DCA0356FB4F36B19B07696B8041D2E64A561F0E68F67C77F237',
	X_SICES_API_PASS:'51793c7af7043d16ae275694ce39c9070b878f8651211aa2197f06cc1fa86680',
};

export default config;
